export const environment = {
	title: "Local Environment Heading",
	apiURL: "https://shopfloor-api-sweet-bear-ea.cfapps.us10.hana.ondemand.com/odata",
	apiPrefix: "odata",
	apiPrefixForRest: "https://shopfloor-api-sweet-bear-ea.cfapps.us10.hana.ondemand.com/api",
	soketiHost: "localhost",
	soketiPort: 6001,
	soketiPath: "",
	soketiAppKey: "app-key",
	homeLink: "/",
	v12HomeLink: "/",
	isLogoutHide: false,
	isV9enable: false,
	isV10enable: true,
	homeLogo: "schertech",
	isHomeLogoCustom: 0,
	isPlanVisuGanttRestrictionRemove: false,
	clientName : '',
	isToolRepairProductionDateManual: true,
};
