export const Localization = {
    recordSavedSuccessfully:  $localize`Record saved successfully!`,
    failedToSaveData:$localize`Failed to save data!`,
    recordDeleted:  $localize`Record deleted!`,
    invalidEntry: $localize`Invalid entry.`,
    idIsAlreadyTaken: $localize`ID is already taken.`,
    emailIsAlreadyTaken: $localize`Email is already taken.`,
    thisEntryIsBeingUsedElsewhere: $localize`This entry is being used elsewhere!.`,
    doYouWantToDeleteThisRecord: $localize`Do you want to delete this Record?`,
    doYouWantToSaveThisRecord: $localize`Do you really want to save the changes?`,
    doYouWantToRemoveAllTheChanges: $localize`Do you really want to remove all the changes?`,
    someThingWentWrong: $localize`Something went wrong!`,
    idIsRequired:$localize`ID is required.`,
    shiftsTimeOverlapped: $localize`Shifts Time Overlapped!`,
    id: $localize`ID`,
    name: $localize`Name`,
    active: $localize`Active`,
    add: $localize`Add`,
    edit: $localize`Edit`,
    delete: $localize`Delete`,
    internalServerError: $localize`Internal Server Error`,
    recordExist: $localize`This record is already exists.`,
    ok: $localize`Ok`,
    close: $localize`Close`,
    save: $localize`Save`,
    update: $localize`Update`,
    cancel: $localize`Cancel`,
    yes: $localize`Yes`,
    no: $localize`No`,
    chat: $localize`Chat`,
    aiAssists: $localize`AI Assists`,
    kvp: $localize`KVP`,
    all: $localize`All`,
    open: $localize`Open`,
    go: $localize`Go`,
    reset: $localize`Reset`,
    upload: $localize`Upload`,
    download: $localize`Download`,
    warning: $localize`Warning`,
    details: $localize`Details`,
    nameIsRequired: $localize`Name is required`,
    autoPostGoodsReceipt: $localize`Auto-Post Goods Receipt`,
    allUnsavedChangesWillBeLost: $localize `All unsaved changes will be lost. Are you sure?`
  };

