import { DateHelper } from "@bryntum/core-thin";

 const presets: any = [
		{
			id: "year-30by100",
			name: "Years",
			tickWidth: 30,
			tickHeight: 100,
			displayDateFormat: "MMM DD, YYYY, HH:mm",
			shiftUnit: "year",
			shiftIncrement: 1,
			defaultSpan: 1,
			mainUnit: "year",
			timeResolution: {
				unit: "month",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "year",
					dateFormat: "YYYY",
					originalDateFormat: "YYYY",
				},
				{
					increment: 1,
					unit: "quarter",
					dateFormat: "QX",
				},
			],
			mainHeaderLevel: 0,
			columnLinesFor: 1,
		},
		{
			id: "year-50by100",
			name: "Years",
			tickWidth: 50,
			tickHeight: 100,
			displayDateFormat: "MMM DD, YYYY, HH:mm",
			shiftUnit: "year",
			shiftIncrement: 1,
			defaultSpan: 1,
			mainUnit: "year",
			timeResolution: {
				unit: "month",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "year",
					dateFormat: "YYYY",
					originalDateFormat: "YYYY",
				},
				{
					increment: 1,
					dateFormat: "QX",
					unit: "quarter",
				},
			],
			mainHeaderLevel: 0,
			columnLinesFor: 1,
		},
		{
			id: "year",
			name: "Years",
			tickWidth: 100,
			tickHeight: 100,
			displayDateFormat: "MMM DD, YYYY, HH:mm",
			shiftUnit: "year",
			shiftIncrement: 1,
			defaultSpan: 1,
			mainUnit: "year",
			timeResolution: {
				unit: "month",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "year",
					dateFormat: "YYYY",
					originalDateFormat: "YYYY",
				},
				{
					increment: 1,
					unit: "quarter",
					dateFormat: "QX",
				},
			],
			mainHeaderLevel: 0,
			columnLinesFor: 1,
		},
		{
			id: "year-200by100",
			name: "Years",
			tickWidth: 200,
			tickHeight: 100,
			displayDateFormat: "MMM DD",
			shiftUnit: "year",
			shiftIncrement: 1,
			defaultSpan: 1,
			mainUnit: "year",
			timeResolution: {
				unit: "second",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "year",
					dateFormat: "YYYY",
					originalDateFormat: "YYYY",
				},
				{
					increment: 1,
					unit: "quarter",
					dateFormat: "QX",
				},
			],
			mainHeaderLevel: 0,
			columnLinesFor: 1,
		},
		{
			id: "monthAndYear",
			name: "Months",
			tickWidth: 110,
			tickHeight: 110,
			displayDateFormat: "MMM DD, YYYY, HH:mm",
			shiftUnit: "month",
			shiftIncrement: 3,
			defaultSpan: 12,
			mainUnit: "month",
			timeResolution: {
				unit: "second",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "year",
					dateFormat: "YYYY",
					originalDateFormat: "YYYY",
				},
				{
					increment: 1,
					unit: "month",
					dateFormat: "MMM YYYY",
					originalDateFormat: "MMM YYYY",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 1,
		},
		{
			id: "weekDateAndMonth",
			name: "Months/weeks",
			tickWidth: 30,
			tickHeight: 40,
			displayDateFormat: "MMM DD, YYYY, HH:mm",
			shiftUnit: "week",
			shiftIncrement: 1,
			defaultSpan: 10,
			mainUnit: "week",
			timeResolution: {
				unit: "second",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "month",
					dateFormat: "YYYY MMMM",
					originalDateFormat: "YYYY MMMM",
				},
				{
					unit: "week",
					// dateFormat: "WW",
					renderer: (startDate: any) => {
						return `${DateHelper.format(startDate, "WW")}`;
					},
					align: "center",
					increment: 1,
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 1,
		},
		{
			id: "weekDateAndMonth2",
			name: "Months/weeks",
			tickWidth: 50,
			tickHeight: 40,
			displayDateFormat: "MMM DD, YYYY, HH:mm",
			shiftUnit: "week",
			shiftIncrement: 1,
			defaultSpan: 10,
			mainUnit: "week",
			timeResolution: {
				unit: "second",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "month",
					dateFormat: "YYYY MMMM",
					originalDateFormat: "YYYY MMMM",
				},
				{
					unit: "week",
					// dateFormat: "WW",
					renderer: (startDate: any) => {
						return `${DateHelper.format(startDate, "WW")}`;
					},
					align: "center",
					increment: 1,
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 1,
		},
		{
			id: "weekAndMonth1",
			name: "Weeks",
			tickWidth: 80,
			tickHeight: 105,
			displayDateFormat: "MMM DD, YYYY, HH:mm",
			shiftUnit: "week",
			shiftIncrement: 5,
			defaultSpan: 6,
			mainUnit: "week",
			timeResolution: {
				unit: "second",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "month",
					dateFormat: "MMMM YYYY",
					originalDateFormat: "MMMM YYYY",
				},
				{
					unit: "week",
					// dateFormat: "WW",
					renderer: (startDate: any) => {
						return $localize`Week` + ` ${DateHelper.format(startDate, "WW")}`;
					},
					align: "center",
					increment: 1,
				},
				{
					unit: "day",
					dateFormat: "DD",
					align: "center",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 2,
		},
		{
			id: "weekAndDayLetter1",
			name: "Weeks/weekdays",
			tickWidth: 20,
			tickHeight: 50,
			displayDateFormat: "MMM DD, YYYY, HH:mm",
			shiftUnit: "week",
			shiftIncrement: 1,
			defaultSpan: 10,
			mainUnit: "week",
			timeResolution: {
				unit: "second",
				increment: 0,
			},
			headers: [
				{
					unit: "month",
					// dateFormat: "WW",
					dateFormat: "MMM",
					align: "center",
					increment: 1,
				},
				{
					unit: "week",
					// dateFormat: "WW",
					renderer: (startDate: any) => {
						return $localize`Week` + ` ${DateHelper.format(startDate, "WW")}`;
					},
					align: "center",
					increment: 1,
				},
				{
					increment: 1,
					unit: "day",
					dateFormat: "d1",
					verticalColumnWidth: 25,
					originalDateFormat: "d1",
				},
			],
			mainHeaderLevel: 0,
			columnLinesFor: 2,
		},
		{
			id: "weekAndDay-54by80",
			name: "Week",
			tickWidth: 54,
			tickHeight: 80,
			displayDateFormat: "MMM DD, YYYY, HH:mm HH:mm",
			shiftUnit: "week",
			shiftIncrement: 1,
			defaultSpan: 1,
			mainUnit: "week",
			timeResolution: {
				unit: "hour",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "month",
					dateFormat: "MMMM YYYY",
					originalDateFormat: "MMMM YYYY",
				},
				{
					unit: "week",
					// dateFormat: "WW",
					renderer: (startDate: any) => {
						return $localize`Week` + ` ${DateHelper.format(startDate, "WW")}`;
					},
					align: "center",
					increment: 1,
				},
				{
					unit: "day",
					increment: 1,
					dateFormat: "DD",
					originalDateFormat: "DD",
				},
			],
			mainHeaderLevel: 0,
			columnLinesFor: 2,
		},
		{
			id: "weekAndDay-54by802",
			name: "Week",
			tickWidth: 100,
			tickHeight: 80,
			displayDateFormat: "MMM DD, YYYY, HH:mm HH:mm",
			shiftUnit: "week",
			shiftIncrement: 1,
			defaultSpan: 1,
			mainUnit: "week",
			timeResolution: {
				unit: "hour",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "month",
					dateFormat: "MMMM YYYY",
					originalDateFormat: "MMMM YYYY",
				},
				{
					unit: "week",
					// dateFormat: "WW",
					renderer: (startDate: any) => {
						return $localize`Week` + ` ${DateHelper.format(startDate, "WW")}`;
					},
					align: "center",
					increment: 1,
				},
				{
					unit: "day",
					increment: 1,
					dateFormat: "DD",
					originalDateFormat: "DD",
				},
			],
			mainHeaderLevel: 0,
			columnLinesFor: 2,
		},
		{
			id: "weekAndDay-54by803",
			name: "Week",
			tickWidth: 100,
			tickHeight: 80,
			displayDateFormat: "MMM DD, YYYY, HH:mm HH:mm",
			shiftUnit: "week",
			shiftIncrement: 1,
			defaultSpan: 1,
			mainUnit: "week",
			timeResolution: {
				unit: "hour",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "month",
					dateFormat: "MMMM YYYY",
					originalDateFormat: "MMMM YYYY",
				},
				{
					unit: "week",
					// dateFormat: "WW",
					renderer: (startDate: any) => {
						return $localize`Week` + ` ${DateHelper.format(startDate, "WW")}`;
					},
					align: "center",
					increment: 1,
				},
				{
					unit: "day",
					increment: 1,
					dateFormat: "DD",
					originalDateFormat: "DD",
				},
			],
			mainHeaderLevel: 0,
			columnLinesFor: 2,
		},
		{
			id: "dayAndMonth1",
			name: "Month1",
			tickWidth: 100,
			tickHeight: 80,
			displayDateFormat: "MMM DD, YYYY, HH:mm HH:mm",
			shiftUnit: "month",
			shiftIncrement: 1,
			defaultSpan: 1,
			mainUnit: "month",
			timeResolution: {
				unit: "second",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "month",
					dateFormat: "MMMM YYYY",
					originalDateFormat: "MMMM YYYY",
				},
				{
					unit: "week",
					// dateFormat: "WW",
					renderer: (startDate: any) => {
						return $localize`Week` + ` ${DateHelper.format(startDate, "WW")}`;
					},
					align: "center",
					increment: 1,
				},

				{
					increment: 1,
					unit: "day",
					dateFormat: "DD",
					originalDateFormat: "DD",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 2,
		},
		{
			id: "weekAndDay1",
			name: "Week1",
			tickWidth: 90,
			tickHeight: 80,
			displayDateFormat: "MMM DD, YYYY, HH:mm HH:mm",
			shiftUnit: "week",
			shiftIncrement: 1,
			defaultSpan: 1,
			mainUnit: "week",
			timeResolution: {
				unit: "second",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "month",
					dateFormat: "MMMM YYYY",
					originalDateFormat: "MMMM YYYY",
				},
				{
					unit: "week",
					// dateFormat: "WW",
					renderer: (startDate: any) => {
						return $localize`Week` + ` ${DateHelper.format(startDate, "WW")}`;
					},
					align: "center",
					increment: 1,
				},
				{
					unit: "day",
					increment: 1,
					dateFormat: "DD",
					originalDateFormat: "DD",
				},
			],
			mainHeaderLevel: 0,
			columnLinesFor: 2,
		},
		{
			id: "dayAndweekAndMonth1",
			name: "Weeks",
			tickWidth: 140,
			tickHeight: 105,
			displayDateFormat: "MMM DD, YYYY, HH:mm",
			shiftUnit: "day",
			shiftIncrement: 3,
			// defaultSpan: 1,
			mainUnit: "day",

			timeResolution: {
				unit: "second",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "month",
					dateFormat: "MMMM YYYY",
					align: "center",
				},
				{
					unit: "week",
					// dateFormat: "WW",
					renderer: (startDate: any) => {
						return $localize`Week` + ` ${DateHelper.format(startDate, "WW")}`;
					},
					align: "center",
				},
				{
					increment: 1,
					unit: "day",
					dateFormat: "DD",
					align: "center",
				},
			],
			mainHeaderLevel: 2,
			columnLinesFor: 2,
		},
		{
			id: "dayAndweekAndMonth12",
			name: "Weeks",
			tickWidth: 150,
			tickHeight: 105,
			displayDateFormat: "MMM DD, YYYY, HH:mm",
			shiftUnit: "day",
			shiftIncrement: 3,
			// defaultSpan: 1,
			mainUnit: "day",

			timeResolution: {
				unit: "second",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "month",
					dateFormat: "MMMM YYYY",
					align: "center",
				},
				{
					unit: "week",
					// dateFormat: "WW",
					renderer: (startDate: any) => {
						return $localize`Week` + ` ${DateHelper.format(startDate, "WW")}`;
					},
					align: "center",
				},
				{
					increment: 1,
					unit: "day",
					dateFormat: "DD",
					align: "center",
				},
			],
			// mainHeaderLevel: 1,
		},
		{
			id: "hourAndDay-64by4022",
			name: "Day",
			tickWidth: 54,
			tickHeight: 40,
			displayDateFormat: "MMM DD, YYYY, HH:mm HH:mm",
			shiftUnit: "day",
			shiftIncrement: 1,
			defaultSpan: 24,
			mainUnit: "hour",
			timeResolution: {
				unit: "minute",
				increment: 0,
			},
			headers: [
				{
					unit: "week",
					// dateFormat: "WW",
					renderer: (startDate: any) => {
						return $localize`Week` + ` ${DateHelper.format(startDate, "WW")}`;
					},
					align: "center",
				},
				{
					increment: 1,
					unit: "day",
					dateFormat: "ddd MM/DD",
					originalDateFormat: "ddd DD/MM",
				},
				{
					increment: 6,
					unit: "hour",
					dateFormat: "HH:mm",
					originalDateFormat: "HH:mm",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 2,
		},
		{
			id: "hourAndDay-64by40",
			name: "Day",
			tickWidth: 64,
			tickHeight: 40,
			displayDateFormat: "MMM DD, YYYY, HH:mm HH:mm",
			shiftUnit: "day",
			shiftIncrement: 1,
			defaultSpan: 24,
			mainUnit: "hour",
			timeResolution: {
				unit: "minute",
				increment: 0,
			},
			headers: [
				{
					unit: "week",
					// dateFormat: "WW",
					renderer: (startDate: any) => {
						return $localize`Week` + ` ${DateHelper.format(startDate, "WW")}`;
					},
					align: "center",
				},
				{
					increment: 1,
					unit: "day",
					dateFormat: "ddd MM/DD",
					originalDateFormat: "ddd DD/MM",
				},
				{
					increment: 6,
					unit: "hour",
					dateFormat: "HH:mm",
					originalDateFormat: "HH:mm",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 2,
		},
		{
			id: "hourAndDay-100by40",
			name: "Day",
			tickWidth: 100,
			tickHeight: 40,
			displayDateFormat: "MMM DD, YYYY, HH:mm HH:mm",
			shiftUnit: "day",
			shiftIncrement: 1,
			defaultSpan: 24,
			mainUnit: "hour",
			timeResolution: {
				unit: "minute",
				increment: 0,
			},
			headers: [
				{
					unit: "week",
					// dateFormat: "WW",
					renderer: (startDate: any) => {
						return $localize`Week` + ` ${DateHelper.format(startDate, "WW")}`;
					},
					align: "center",
				},
				{
					increment: 1,
					unit: "day",
					dateFormat: "ddd MM/DD",
					originalDateFormat: "ddd DD/MM",
				},
				{
					increment: 6,
					unit: "hour",
					dateFormat: "HH:mm",
					originalDateFormat: "HH:mm",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 2,
		},
		{
			id: "hourAndDay-64by40-2",
			name: "Day",
			tickWidth: 64,
			tickHeight: 40,
			displayDateFormat: "MMM DD, YYYY, HH:mm HH:mm",
			shiftUnit: "day",
			shiftIncrement: 1,
			defaultSpan: 24,
			mainUnit: "hour",
			timeResolution: {
				unit: "minute",
				increment: 0,
			},
			headers: [
				{
					unit: "week",
					// dateFormat: "WW",
					renderer: (startDate: any) => {
						return $localize`Week` + ` ${DateHelper.format(startDate, "WW")}`;
					},
					align: "center",
				},
				{
					increment: 1,
					unit: "day",
					dateFormat: "ddd MM/DD",
					originalDateFormat: "ddd DD/MM",
				},
				{
					increment: 2,
					unit: "hour",
					dateFormat: "HH:mm",
					originalDateFormat: "HH:mm",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 2,
		},
		// {
		// 	id: "hourAndDay",
		// 	name: "Day",
		// 	tickWidth: 70,
		// 	tickHeight: 40,
		// 	displayDateFormat: "MMM DD, YYYY, HH:mm HH:mm",
		// 	shiftUnit: "day",
		// 	shiftIncrement: 1,
		// 	defaultSpan: 24,
		// 	mainUnit: "hour",
		// 	timeResolution: {
		// 		unit: "minute",
		// 	},
		// 	headers: [
		// 		{
		// 			unit: "week",
		// 			// dateFormat: "WW",
		// 			renderer: (startDate: any) => {
		// 				return $localize`Week` + ` ${DateHelper.format(startDate, "WW")}`;
		// 			},
		// 			align: "center",
		// 		},
		// 		{
		// 			increment: 1,
		// 			unit: "day",
		// 			dateFormat: "ddd MM/DD",
		// 			originalDateFormat: "ddd DD/MM",
		// 		},
		// 		{
		// 			increment: 1,
		// 			unit: "hour",
		// 			dateFormat: "HH:mm",
		// 			originalDateFormat: "HH:mm",
		// 		},
		// 	],
		// 	mainHeaderLevel: 1,
		// 	columnLinesFor: 1,
		// },
		{
			id: "minuteAndHour1",
			name: "Minutes",
			tickWidth: 60,
			tickHeight: 60,
			displayDateFormat: "MMM DD, YYYY, HH:mm",
			shiftUnit: "hour",
			shiftIncrement: 1,
			defaultSpan: 24,
			mainUnit: "minute",
			timeResolution: {
				unit: "minute",
			},
			headers: [
				{
					increment: 1,
					unit: "hour",
					dateFormat: "ddd MM/DD",
					originalDateFormat: "ddd MM/DD",
				},
				{
					unit: "minute",
					increment: 30,
					dateFormat: "H:mm",
					originalDateFormat: "H:mm",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 1,
		},
		{
			id: "minuteAndHour-60by60",
			name: "Minutes",
			tickWidth: 60,
			tickHeight: 60,
			displayDateFormat: "MMM DD, YYYY, HH:mm HH:mm",
			shiftUnit: "hour",
			shiftIncrement: 1,
			defaultSpan: 24,
			mainUnit: "minute",
			timeResolution: {
				unit: "minute",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "hour",
					dateFormat: "ddd MM/DD, H",
					originalDateFormat: "ddd MM/DD, H",
				},
				{
					unit: "minute",
					increment: 15,
					dateFormat: "mm",
					originalDateFormat: "mm",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 1,
		},
		{
			id: "minuteAndHour-130by60",
			name: "Minutes",
			tickWidth: 130,
			tickHeight: 60,
			displayDateFormat: "MMM DD, YYYY, HH:mm HH:mm",
			shiftUnit: "hour",
			shiftIncrement: 1,
			defaultSpan: 24,
			mainUnit: "minute",
			timeResolution: {
				unit: "minute",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "hour",
					dateFormat: "ddd MM/DD, H",
					originalDateFormat: "ddd MM/DD, H",
				},
				{
					unit: "minute",
					increment: 15,
					dateFormat: "mm",
					originalDateFormat: "mm",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 1,
		},
		{
			id: "minuteAndHour-60by60-5",
			name: "Minutes",
			tickWidth: 60,
			tickHeight: 60,
			displayDateFormat: "MMM DD, YYYY, HH:mm HH:mm",
			shiftUnit: "hour",
			shiftIncrement: 1,
			defaultSpan: 24,
			mainUnit: "minute",
			timeResolution: {
				unit: "minute",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "hour",
					dateFormat: "ddd MM/DD, H",
					originalDateFormat: "ddd MM/DD, H",
				},
				{
					unit: "minute",
					increment: 5,
					dateFormat: "mm",
					originalDateFormat: "mm",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 1,
		},
		{
			id: "minuteAndHour-100by60",
			name: "Minutes",
			tickWidth: 100,
			tickHeight: 60,
			displayDateFormat: "MMM DD, YYYY, HH:mm HH:mm",
			shiftUnit: "hour",
			shiftIncrement: 1,
			defaultSpan: 24,
			mainUnit: "minute",
			timeResolution: {
				unit: "minute",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "hour",
					dateFormat: "ddd MM/DD, H",
					originalDateFormat: "ddd MM/DD, H",
				},
				{
					unit: "minute",
					increment: 5,
					dateFormat: "mm",
					originalDateFormat: "mm",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 1,
		},
		{
			id: "minuteAndHour-100by602",
			name: "Minutes",
			tickWidth: 130,
			tickHeight: 90,
			displayDateFormat: "MMM DD, YYYY, HH:mm HH:mm",
			shiftUnit: "hour",
			shiftIncrement: 1,
			defaultSpan: 24,
			mainUnit: "minute",
			timeResolution: {
				unit: "minute",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "hour",
					dateFormat: "ddd MM/DD, H",
					originalDateFormat: "ddd MM/DD, H",
				},
				{
					unit: "minute",
					increment: 5,
					dateFormat: "mm",
					originalDateFormat: "mm",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 1,
		},
		{
			id: "minuteAndHour-100by603",
			name: "Minutes",
			tickWidth: 160,
			tickHeight: 90,
			displayDateFormat: "MMM DD, YYYY, HH:mm HH:mm",
			shiftUnit: "hour",
			shiftIncrement: 1,
			defaultSpan: 24,
			mainUnit: "minute",
			timeResolution: {
				unit: "minute",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "hour",
					dateFormat: "ddd MM/DD, H",
					originalDateFormat: "ddd MM/DD, H",
				},
				{
					unit: "minute",
					increment: 5,
					dateFormat: "mm",
					originalDateFormat: "mm",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 1,
		},
		{
			id: "minuteAndHour-100by604",
			name: "Minutes",
			tickWidth: 200,
			tickHeight: 90,
			displayDateFormat: "MMM DD, YYYY, HH:mm HH:mm",
			shiftUnit: "hour",
			shiftIncrement: 1,
			defaultSpan: 24,
			mainUnit: "minute",
			timeResolution: {
				unit: "minute",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "hour",
					dateFormat: "ddd MM/DD, H",
					originalDateFormat: "ddd MM/DD, H",
				},
				{
					unit: "minute",
					increment: 5,
					dateFormat: "mm",
					originalDateFormat: "mm",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 1,
		},
		{
			id: "secondAndMinute",
			name: "Seconds",
			tickWidth: 30,
			tickHeight: 40,
			displayDateFormat: "MMM DD, YYYY, HH:mm",
			shiftUnit: "minute",
			shiftIncrement: 10,
			defaultSpan: 24,
			mainUnit: "second",
			timeResolution: {
				unit: "second",
			},
			headers: [
				{
					increment: 1,
					unit: "minute",
					dateFormat: "MMM DD, YYYY, HH:mm",
					originalDateFormat: "MMM DD, YYYY, HH:mm",
				},
				{
					unit: "second",
					increment: 10,
					dateFormat: "ss",
					originalDateFormat: "ss",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 1,
		},
		{
			id: "secondAndMinute-60by40",
			name: "Seconds",
			tickWidth: 60,
			tickHeight: 40,
			displayDateFormat: "MMM DD, YYYY, HH:mm",
			shiftUnit: "minute",
			shiftIncrement: 10,
			defaultSpan: 24,
			mainUnit: "second",
			timeResolution: {
				unit: "second",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "minute",
					dateFormat: "MMM DD, YYYY, HH:mm",
					originalDateFormat: "MMM DD, YYYY, HH:mm",
				},
				{
					unit: "second",
					increment: 10,
					dateFormat: "ss",
					originalDateFormat: "ss",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 1,
		},
		{
			id: "secondAndMinute-130by40",
			name: "Seconds",
			tickWidth: 130,
			tickHeight: 40,
			displayDateFormat: "MMM DD, YYYY, HH:mm",
			shiftUnit: "minute",
			shiftIncrement: 10,
			defaultSpan: 24,
			mainUnit: "second",
			timeResolution: {
				unit: "second",
				increment: 0,
			},
			headers: [
				{
					increment: 1,
					unit: "minute",
					dateFormat: "MMM DD, YYYY, HH:mm",
					originalDateFormat: "MMM DD, YYYY, HH:mm",
				},
				{
					unit: "second",
					increment: 5,
					dateFormat: "ss",
					originalDateFormat: "ss",
				},
			],
			mainHeaderLevel: 1,
			columnLinesFor: 1,
		},
 ];

export default presets;
