export enum Kpi {
	PROD_TIME = "PROD_TIME",
	CAPACITY = "CAPACITY",
	TARGET_TIME = "TARGET_TIME",
	QUANTITY_GOOD = "QUANTITY_GOOD",
	QUANTITY_BAD = "QUANTITY_BAD",
	QUANTITY_TOTAL = "QUANTITY_TOTAL",
	MACHINE_USAGE = "MACHINE_USAGE",
	MACHINE_PERFORMANCE = "MACHINE_PERFORMANCE",
	QUALITY = "QUALITY",
	SCRAP = "SCRAP",
	OEE = "OEE",
}
