/*
  Example Usage:
  * Author: Mr. Omer Arafat
  To retrieve Bar Allownece for a given value,
  use the following code:
  
  const value = **;
  const result = new BarAllowance().findValue(value);
  
  If a matching range is found, 'result' will contain the Ring object.
  Otherwise, it will be null.
*/


export class BarAllowance {
    private rowRanges: number[][] = [
        [0, 2499],
        [2500, 4500],
        [4501, 6000],
        [6001, 7500]
    ];

	private columnRanges: number[][] = [
        [60, 80],
        [81, 100],
        [101, 120],
        [121, 140],
        [141, 160],
        [161, 175],
        [176, 190],
        [191, 210],
        [211, 230],
        [231, 245],
        [246, 260],
        [261, 280],
        [281, 300],
        [301, 320],
        [321, 340],
        [341, 360],
        [361, 400],
        [401, 415],
        [416, 430],
        [431, 445],
        [446, 460],
        [461, 475],
        [476, 500],
        [501, 520],
        [521, 540],
        [541, 560],
        [561, 580],
        [581, 600],
        [601, 620],
        [621, 640],
        [641, 660],
        [661, 680],
        [681, 700],
        [701, 720],
        [721, 740],
        [741, 760],
        [761, 780],
        [781, 800],
        [801, 820],
        [821, 840],
        [841, 860],
        [861, 880],
        [881, 900],
        [901, 920],
        [921, 940],
        [941, 960],
        [961, 980],
        [981, 1000],
        [1001, 1025],
        [1026, 1050],
        [1051, 1075],
        [1076, 1100],
        [1101, 1125],
        [1126, 1150],
        [1151, 1175],
        [1180, 1200],
        [1201, 1225],
        [1226, 1250],
        [1251, 1275],
        [1276, 1300],
        [1301, 1325],
        [1326, 1350],
        [1351, 1375],
        [1376, 1400],
        [1401, 1425],
        [1426, 1450],
        [1451, 1475],
        [1476, 1500],
        [1501, 1525],
        [1526, 1550],
        [1551, 1575],
        [1576, 1600],
        [1601, 1625],
        [1626, 1650],
        [1651, 1675],
        [1676, 1700],
        [1701, 1725],
        [1726, 1750],
        [1751, 1775],
        [1776, 1800],
        [1801, 1820],
        [1821, 1840],
        [1841, 1860],
        [1861, 1880],
        [1881, 1900],
        [1901, Infinity]
    ];    

	// Tolarence values can be adjusted with a tolerance of (+) or (-)
	private grid: { roundAllowance: number; length: number, roundTolerance: number, lengthTolerance: number }[][] = [
        [
            { roundAllowance: 10, length: 14, roundTolerance: 2, lengthTolerance: 4 },
            { roundAllowance: 11, length: 15, roundTolerance: 2, lengthTolerance: 4 },
            { roundAllowance: 12, length: 16, roundTolerance: 2, lengthTolerance: 4 },
            { roundAllowance: 13, length: 17, roundTolerance: 3, lengthTolerance: 4 },
            { roundAllowance: 14, length: 18, roundTolerance: 3, lengthTolerance: 5 },
            { roundAllowance: 15, length: 19, roundTolerance: 3, lengthTolerance: 5 },
            { roundAllowance: 16, length: 20, roundTolerance: 3, lengthTolerance: 5 },
            { roundAllowance: 17, length: 21, roundTolerance: 3, lengthTolerance: 5 },
            { roundAllowance: 18, length: 22, roundTolerance: 4, lengthTolerance: 6 },
            { roundAllowance: 19, length: 23, roundTolerance: 4, lengthTolerance: 6 },
            { roundAllowance: 20, length: 24, roundTolerance: 4, lengthTolerance: 6 },
            { roundAllowance: 21, length: 25, roundTolerance: 4, lengthTolerance: 6 },
            { roundAllowance: 22, length: 26, roundTolerance: 4, lengthTolerance: 7 },
            { roundAllowance: 23, length: 27, roundTolerance: 5, lengthTolerance: 7 },
            { roundAllowance: 24, length: 28, roundTolerance: 5, lengthTolerance: 7 },
            { roundAllowance: 25, length: 29, roundTolerance: 5, lengthTolerance: 7 },
            { roundAllowance: 26, length: 30, roundTolerance: 5, lengthTolerance: 8 },
            { roundAllowance: 27, length: 31, roundTolerance: 5, lengthTolerance: 8 },
            { roundAllowance: 28, length: 32, roundTolerance: 6, lengthTolerance: 8 },
            { roundAllowance: 29, length: 33, roundTolerance: 6, lengthTolerance: 8 },
            { roundAllowance: 30, length: 34, roundTolerance: 6, lengthTolerance: 9 },
            { roundAllowance: 31, length: 35, roundTolerance: 6, lengthTolerance: 9 },
            { roundAllowance: 32, length: 36, roundTolerance: 6, lengthTolerance: 9 },
            { roundAllowance: 33, length: 37, roundTolerance: 7, lengthTolerance: 9 },
            { roundAllowance: 34, length: 38, roundTolerance: 7, lengthTolerance: 10 },
            { roundAllowance: 35, length: 39, roundTolerance: 7, lengthTolerance: 10 },
            { roundAllowance: 36, length: 40, roundTolerance: 7, lengthTolerance: 10 },
            { roundAllowance: 37, length: 41, roundTolerance: 7, lengthTolerance: 10 },
            { roundAllowance: 38, length: 42, roundTolerance: 8, lengthTolerance: 11 },
            { roundAllowance: 39, length: 43, roundTolerance: 8, lengthTolerance: 11 },
            { roundAllowance: 40, length: 44, roundTolerance: 8, lengthTolerance: 11 },
            { roundAllowance: 41, length: 45, roundTolerance: 8, lengthTolerance: 11 },
            { roundAllowance: 42, length: 46, roundTolerance: 8, lengthTolerance: 12 },
            { roundAllowance: 43, length: 47, roundTolerance: 9, lengthTolerance: 12 },
            { roundAllowance: 44, length: 48, roundTolerance: 9, lengthTolerance: 12 },
            { roundAllowance: 45, length: 49, roundTolerance: 9, lengthTolerance: 12 },
            { roundAllowance: 46, length: 50, roundTolerance: 9, lengthTolerance: 13 },
            { roundAllowance: 47, length: 51, roundTolerance: 9, lengthTolerance: 13 },
            { roundAllowance: 48, length: 52, roundTolerance: 10, lengthTolerance: 13 },
            { roundAllowance: 49, length: 53, roundTolerance: 10, lengthTolerance: 13 },
            { roundAllowance: 50, length: 54, roundTolerance: 10, lengthTolerance: 14 },
            { roundAllowance: 51, length: 55, roundTolerance: 10, lengthTolerance: 14 },
            { roundAllowance: 52, length: 56, roundTolerance: 10, lengthTolerance: 14 },
            { roundAllowance: 53, length: 57, roundTolerance: 11, lengthTolerance: 14 },
            { roundAllowance: 54, length: 58, roundTolerance: 11, lengthTolerance: 15 },
            { roundAllowance: 55, length: 59, roundTolerance: 11, lengthTolerance: 15 },
            { roundAllowance: 56, length: 60, roundTolerance: 11, lengthTolerance: 15 },
            { roundAllowance: 57, length: 61, roundTolerance: 11, lengthTolerance: 15 },
            { roundAllowance: 58, length: 62, roundTolerance: 12, lengthTolerance: 16 },
            { roundAllowance: 59, length: 63, roundTolerance: 12, lengthTolerance: 16 },
            { roundAllowance: 60, length: 64, roundTolerance: 12, lengthTolerance: 16 },
            { roundAllowance: 61, length: 65, roundTolerance: 12, lengthTolerance: 16 },
            { roundAllowance: 62, length: 66, roundTolerance: 12, lengthTolerance: 17 },
            { roundAllowance: 63, length: 67, roundTolerance: 13, lengthTolerance: 17 },
            { roundAllowance: 64, length: 68, roundTolerance: 13, lengthTolerance: 17 },
            { roundAllowance: 65, length: 69, roundTolerance: 13, lengthTolerance: 17 },
            { roundAllowance: 67, length: 70, roundTolerance: 13, lengthTolerance: 18 },
            { roundAllowance: 69, length: 71, roundTolerance: 14, lengthTolerance: 18 },
            { roundAllowance: 71, length: 72, roundTolerance: 14, lengthTolerance: 18 },
            { roundAllowance: 73, length: 73, roundTolerance: 15, lengthTolerance: 18 },
            { roundAllowance: 75, length: 74, roundTolerance: 15, lengthTolerance: 19 },
            { roundAllowance: 77, length: 75, roundTolerance: 15, lengthTolerance: 19 },
            { roundAllowance: 79, length: 76, roundTolerance: 16, lengthTolerance: 19 },
            { roundAllowance: 81, length: 77, roundTolerance: 16, lengthTolerance: 19 },
            { roundAllowance: 82, length: 78, roundTolerance: 16, lengthTolerance: 20 },
            { roundAllowance: 83, length: 79, roundTolerance: 17, lengthTolerance: 20 },
            { roundAllowance: 84, length: 80, roundTolerance: 17, lengthTolerance: 20 },
            { roundAllowance: 85, length: 81, roundTolerance: 17, lengthTolerance: 20 },
            { roundAllowance: 86, length: 82, roundTolerance: 17, lengthTolerance: 21 },
            { roundAllowance: 87, length: 83, roundTolerance: 17, lengthTolerance: 21 },
            { roundAllowance: 88, length: 84, roundTolerance: 18, lengthTolerance: 21 },
            { roundAllowance: 89, length: 85, roundTolerance: 18, lengthTolerance: 21 },
            { roundAllowance: 90, length: 86, roundTolerance: 18, lengthTolerance: 22 },
            { roundAllowance: 91, length: 87, roundTolerance: 18, lengthTolerance: 22 },
            { roundAllowance: 92, length: 88, roundTolerance: 18, lengthTolerance: 22 },
            { roundAllowance: 93, length: 89, roundTolerance: 19, lengthTolerance: 22 },
            { roundAllowance: 94, length: 90, roundTolerance: 19, lengthTolerance: 23 },
            { roundAllowance: 95, length: 91, roundTolerance: 19, lengthTolerance: 23 },
            { roundAllowance: 96, length: 92, roundTolerance: 19, lengthTolerance: 23 },
            { roundAllowance: 97, length: 93, roundTolerance: 19, lengthTolerance: 23 },
            { roundAllowance: 98, length: 94, roundTolerance: 20, lengthTolerance: 24 },
            { roundAllowance: 99, length: 95, roundTolerance: 20, lengthTolerance: 24 },
            { roundAllowance: 100, length: 96, roundTolerance: 20, lengthTolerance: 24 },
            { roundAllowance: 101, length: 97, roundTolerance: 20, lengthTolerance: 24 },
            { roundAllowance: 102, length: 98, roundTolerance: 20, lengthTolerance: 25 }
        ],        
        [
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 13, length: 17, roundTolerance: 3, lengthTolerance: 4 },
            { roundAllowance: 14, length: 18, roundTolerance: 3, lengthTolerance: 5 },
            { roundAllowance: 15, length: 19, roundTolerance: 3, lengthTolerance: 5 },
            { roundAllowance: 16, length: 20, roundTolerance: 3, lengthTolerance: 5 },
            { roundAllowance: 17, length: 21, roundTolerance: 3, lengthTolerance: 5 },
            { roundAllowance: 18, length: 22, roundTolerance: 4, lengthTolerance: 6 },
            { roundAllowance: 19, length: 23, roundTolerance: 4, lengthTolerance: 6 },
            { roundAllowance: 20, length: 24, roundTolerance: 4, lengthTolerance: 6 },
            { roundAllowance: 21, length: 25, roundTolerance: 4, lengthTolerance: 6 },
            { roundAllowance: 22, length: 26, roundTolerance: 4, lengthTolerance: 7 },
            { roundAllowance: 23, length: 27, roundTolerance: 5, lengthTolerance: 7 },
            { roundAllowance: 24, length: 28, roundTolerance: 5, lengthTolerance: 7 },
            { roundAllowance: 25, length: 29, roundTolerance: 5, lengthTolerance: 7 },
            { roundAllowance: 26, length: 30, roundTolerance: 5, lengthTolerance: 8 },
            { roundAllowance: 27, length: 31, roundTolerance: 5, lengthTolerance: 8 },
            { roundAllowance: 28, length: 32, roundTolerance: 6, lengthTolerance: 8 },
            { roundAllowance: 29, length: 33, roundTolerance: 6, lengthTolerance: 8 },
            { roundAllowance: 30, length: 34, roundTolerance: 6, lengthTolerance: 9 },
            { roundAllowance: 31, length: 35, roundTolerance: 6, lengthTolerance: 9 },
            { roundAllowance: 32, length: 36, roundTolerance: 6, lengthTolerance: 9 },
            { roundAllowance: 33, length: 37, roundTolerance: 7, lengthTolerance: 9 },
            { roundAllowance: 34, length: 38, roundTolerance: 7, lengthTolerance: 10 },
            { roundAllowance: 35, length: 39, roundTolerance: 7, lengthTolerance: 10 },
            { roundAllowance: 36, length: 40, roundTolerance: 7, lengthTolerance: 10 },
            { roundAllowance: 37, length: 41, roundTolerance: 7, lengthTolerance: 10 },
            { roundAllowance: 38, length: 42, roundTolerance: 8, lengthTolerance: 11 },
            { roundAllowance: 39, length: 43, roundTolerance: 8, lengthTolerance: 11 },
            { roundAllowance: 40, length: 44, roundTolerance: 8, lengthTolerance: 11 },
            { roundAllowance: 41, length: 45, roundTolerance: 8, lengthTolerance: 11 },
            { roundAllowance: 42, length: 46, roundTolerance: 8, lengthTolerance: 12 },
            { roundAllowance: 43, length: 47, roundTolerance: 9, lengthTolerance: 12 },
            { roundAllowance: 44, length: 48, roundTolerance: 9, lengthTolerance: 12 },
            { roundAllowance: 45, length: 49, roundTolerance: 9, lengthTolerance: 12 },
            { roundAllowance: 46, length: 50, roundTolerance: 9, lengthTolerance: 13 },
            { roundAllowance: 47, length: 51, roundTolerance: 9, lengthTolerance: 13 },
            { roundAllowance: 48, length: 52, roundTolerance: 10, lengthTolerance: 13 },
            { roundAllowance: 49, length: 53, roundTolerance: 10, lengthTolerance: 13 },
            { roundAllowance: 50, length: 54, roundTolerance: 10, lengthTolerance: 14 },
            { roundAllowance: 51, length: 55, roundTolerance: 10, lengthTolerance: 14 },
            { roundAllowance: 52, length: 56, roundTolerance: 10, lengthTolerance: 14},
            { roundAllowance: 53, length: 57, roundTolerance: 11, lengthTolerance: 14 },
            { roundAllowance: 54, length: 58, roundTolerance: 11, lengthTolerance: 15 },
            { roundAllowance: 55, length: 59, roundTolerance: 11, lengthTolerance: 15 },
            { roundAllowance: 56, length: 60, roundTolerance: 11, lengthTolerance: 15 },
            { roundAllowance: 57, length: 61, roundTolerance: 11, lengthTolerance: 15 },
            { roundAllowance: 58, length: 62, roundTolerance: 12, lengthTolerance: 16 },
            { roundAllowance: 59, length: 63, roundTolerance: 12, lengthTolerance: 16 },
            { roundAllowance: 60, length: 64, roundTolerance: 12, lengthTolerance: 16 },
            { roundAllowance: 61, length: 65, roundTolerance: 12, lengthTolerance: 16 },
            { roundAllowance: 62, length: 66, roundTolerance: 12, lengthTolerance: 17 },
            { roundAllowance: 63, length: 67, roundTolerance: 13, lengthTolerance: 17 },
            { roundAllowance: 64, length: 68, roundTolerance: 13, lengthTolerance: 17 },
            { roundAllowance: 65, length: 69, roundTolerance: 13, lengthTolerance: 17 },
            { roundAllowance: 66, length: 70, roundTolerance: 13, lengthTolerance: 18 },
            { roundAllowance: 67, length: 71, roundTolerance: 13, lengthTolerance: 18 },
            { roundAllowance: 69, length: 72, roundTolerance: 14, lengthTolerance: 18 },
            { roundAllowance: 71, length: 73, roundTolerance: 14, lengthTolerance: 18 },
            { roundAllowance: 73, length: 74, roundTolerance: 15, lengthTolerance: 19 },
            { roundAllowance: 75, length: 75, roundTolerance: 15, lengthTolerance: 19 },
            { roundAllowance: 77, length: 76, roundTolerance: 15, lengthTolerance: 19 },
            { roundAllowance: 79, length: 77, roundTolerance: 16, lengthTolerance: 19 },
            { roundAllowance: 81, length: 78, roundTolerance: 16, lengthTolerance: 20 },
            { roundAllowance: 83, length: 79, roundTolerance: 17, lengthTolerance: 20 },
            { roundAllowance: 84, length: 80, roundTolerance: 17, lengthTolerance: 20 },
            { roundAllowance: 85, length: 81, roundTolerance: 17, lengthTolerance: 20 },
            { roundAllowance: 86, length: 82, roundTolerance: 17, lengthTolerance: 21 },
            { roundAllowance: 87, length: 83, roundTolerance: 17, lengthTolerance: 21 },
            { roundAllowance: 88, length: 84, roundTolerance: 18, lengthTolerance: 21 },
            { roundAllowance: 89, length: 85, roundTolerance: 18, lengthTolerance: 21 },
            { roundAllowance: 90, length: 86, roundTolerance: 18, lengthTolerance: 22 },
            { roundAllowance: 91, length: 87, roundTolerance: 18, lengthTolerance: 22 },
            { roundAllowance: 92, length: 88, roundTolerance: 18, lengthTolerance: 22 },
            { roundAllowance: 93, length: 89, roundTolerance: 19, lengthTolerance: 22 },
            { roundAllowance: 94, length: 90, roundTolerance: 19, lengthTolerance: 23 },
            { roundAllowance: 95, length: 91, roundTolerance: 19, lengthTolerance: 23 },
            { roundAllowance: 96, length: 92, roundTolerance: 19, lengthTolerance: 23 },
            { roundAllowance: 97, length: 93, roundTolerance: 19, lengthTolerance: 23 },
            { roundAllowance: 98, length: 94, roundTolerance: 20, lengthTolerance: 24 },
            { roundAllowance: 99, length: 95, roundTolerance: 20, lengthTolerance: 24 },
            { roundAllowance: 100, length: 96, roundTolerance: 20, lengthTolerance: 24 },
            { roundAllowance: 101, length: 97, roundTolerance: 20, lengthTolerance: 24 },
            { roundAllowance: 102, length: 98, roundTolerance: 20, lengthTolerance: 25 },
            { roundAllowance: 103, length: 99, roundTolerance: 21, lengthTolerance: 25 },
            { roundAllowance: 104, length: 100, roundTolerance: 21, lengthTolerance: 25 }
        ],
        [
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 17, length: 21, roundTolerance: 3, lengthTolerance: 5 },
            { roundAllowance: 18, length: 22, roundTolerance: 4, lengthTolerance: 6 },
            { roundAllowance: 19, length: 23, roundTolerance: 4, lengthTolerance: 6 },
            { roundAllowance: 20, length: 24, roundTolerance: 4, lengthTolerance: 6 },
            { roundAllowance: 21, length: 25, roundTolerance: 4, lengthTolerance: 6 },
            { roundAllowance: 22, length: 26, roundTolerance: 4, lengthTolerance: 7 },
            { roundAllowance: 23, length: 27, roundTolerance: 5, lengthTolerance: 7 },
            { roundAllowance: 24, length: 28, roundTolerance: 5, lengthTolerance: 7 },
            { roundAllowance: 25, length: 29, roundTolerance: 5, lengthTolerance: 7 },
            { roundAllowance: 26, length: 30, roundTolerance: 5, lengthTolerance: 8 },
            { roundAllowance: 27, length: 31, roundTolerance: 5, lengthTolerance: 8 },
            { roundAllowance: 28, length: 32, roundTolerance: 6, lengthTolerance: 8 },
            { roundAllowance: 29, length: 33, roundTolerance: 6, lengthTolerance: 8 },
            { roundAllowance: 30, length: 34, roundTolerance: 6, lengthTolerance: 9 },
            { roundAllowance: 31, length: 35, roundTolerance: 6, lengthTolerance: 9 },
            { roundAllowance: 32, length: 36, roundTolerance: 6, lengthTolerance: 9 },
            { roundAllowance: 33, length: 37, roundTolerance: 7, lengthTolerance: 9 },
            { roundAllowance: 34, length: 38, roundTolerance: 7, lengthTolerance: 10 },
            { roundAllowance: 35, length: 39, roundTolerance: 7, lengthTolerance: 10 },
            { roundAllowance: 36, length: 40, roundTolerance: 7, lengthTolerance: 10 },
            { roundAllowance: 37, length: 41, roundTolerance: 7, lengthTolerance: 10 },
            { roundAllowance: 38, length: 42, roundTolerance: 8, lengthTolerance: 11 },
            { roundAllowance: 39, length: 43, roundTolerance: 8, lengthTolerance: 11 },
            { roundAllowance: 40, length: 44, roundTolerance: 8, lengthTolerance: 11 },
            { roundAllowance: 41, length: 45, roundTolerance: 8, lengthTolerance: 11 },
            { roundAllowance: 42, length: 46, roundTolerance: 8, lengthTolerance: 12 },
            { roundAllowance: 43, length: 47, roundTolerance: 9, lengthTolerance: 12 },
            { roundAllowance: 44, length: 48, roundTolerance: 9, lengthTolerance: 12 },
            { roundAllowance: 45, length: 49, roundTolerance: 9, lengthTolerance: 12 },
            { roundAllowance: 46, length: 50, roundTolerance: 9, lengthTolerance: 13 },
            { roundAllowance: 47, length: 51, roundTolerance: 9, lengthTolerance: 13 },
            { roundAllowance: 48, length: 52, roundTolerance: 10, lengthTolerance: 13 },
            { roundAllowance: 49, length: 53, roundTolerance: 10, lengthTolerance: 13 },
            { roundAllowance: 50, length: 54, roundTolerance: 10, lengthTolerance: 14 },
            { roundAllowance: 51, length: 55, roundTolerance: 10, lengthTolerance: 14 },
            { roundAllowance: 52, length: 56, roundTolerance: 10, lengthTolerance: 14 },
            { roundAllowance: 53, length: 57, roundTolerance: 11, lengthTolerance: 14 },
            { roundAllowance: 54, length: 58, roundTolerance: 11, lengthTolerance: 15 },
            { roundAllowance: 55, length: 59, roundTolerance: 11, lengthTolerance: 15 },
            { roundAllowance: 56, length: 60, roundTolerance: 11, lengthTolerance: 15 },
            { roundAllowance: 57, length: 61, roundTolerance: 11, lengthTolerance: 15 },
            { roundAllowance: 58, length: 62, roundTolerance: 12, lengthTolerance: 16 },
            { roundAllowance: 59, length: 63, roundTolerance: 12, lengthTolerance: 16 },
            { roundAllowance: 60, length: 64, roundTolerance: 12, lengthTolerance: 16 },
            { roundAllowance: 61, length: 65, roundTolerance: 12, lengthTolerance: 16 },
            { roundAllowance: 62, length: 66, roundTolerance: 12, lengthTolerance: 17 },
            { roundAllowance: 63, length: 67, roundTolerance: 13, lengthTolerance: 17 },
            { roundAllowance: 64, length: 68, roundTolerance: 13, lengthTolerance: 17 },
            { roundAllowance: 65, length: 69, roundTolerance: 13, lengthTolerance: 17 },
            { roundAllowance: 66, length: 70, roundTolerance: 13, lengthTolerance: 18 },
            { roundAllowance: 67, length: 71, roundTolerance: 13, lengthTolerance: 18 },
            { roundAllowance: 68, length: 72, roundTolerance: 14, lengthTolerance: 18 },
            { roundAllowance: 69, length: 73, roundTolerance: 14, lengthTolerance: 18 },
            { roundAllowance: 71, length: 74, roundTolerance: 15, lengthTolerance: 19 },
            { roundAllowance: 73, length: 74, roundTolerance: 15, lengthTolerance: 19 },
            { roundAllowance: 75, length: 75, roundTolerance: 15, lengthTolerance: 19 },
            { roundAllowance: 77, length: 76, roundTolerance: 15, lengthTolerance: 19 },
            { roundAllowance: 79, length: 77, roundTolerance: 16, lengthTolerance: 19 },
            { roundAllowance: 81, length: 78, roundTolerance: 16, lengthTolerance: 20 },
            { roundAllowance: 83, length: 79, roundTolerance: 17, lengthTolerance: 20 },
            { roundAllowance: 85, length: 81, roundTolerance: 17, lengthTolerance: 20 },
            { roundAllowance: 86, length: 82, roundTolerance: 17, lengthTolerance: 21 },
            { roundAllowance: 87, length: 83, roundTolerance: 17, lengthTolerance: 21 },
            { roundAllowance: 88, length: 84, roundTolerance: 18, lengthTolerance: 21 },
            { roundAllowance: 89, length: 85, roundTolerance: 18, lengthTolerance: 21 },
            { roundAllowance: 90, length: 86, roundTolerance: 18, lengthTolerance: 22 },
            { roundAllowance: 91, length: 87, roundTolerance: 18, lengthTolerance: 22 },
            { roundAllowance: 92, length: 88, roundTolerance: 18, lengthTolerance: 22 },
            { roundAllowance: 93, length: 89, roundTolerance: 19, lengthTolerance: 22 },
            { roundAllowance: 94, length: 90, roundTolerance: 19, lengthTolerance: 23 },
            { roundAllowance: 95, length: 91, roundTolerance: 19, lengthTolerance: 23 },
            { roundAllowance: 96, length: 92, roundTolerance: 19, lengthTolerance: 23 },
            { roundAllowance: 97, length: 93, roundTolerance: 19, lengthTolerance: 23 },
            { roundAllowance: 98, length: 94, roundTolerance: 20, lengthTolerance: 24 },
            { roundAllowance: 99, length: 95, roundTolerance: 20, lengthTolerance: 24 },
            { roundAllowance: 100, length: 96, roundTolerance: 20, lengthTolerance: 24 },
            { roundAllowance: 101, length: 97, roundTolerance: 20, lengthTolerance: 24 },
            { roundAllowance: 102, length: 98, roundTolerance: 20, lengthTolerance: 25 },
            { roundAllowance: 103, length: 99, roundTolerance: 21, lengthTolerance: 25 },
            { roundAllowance: 104, length: 100, roundTolerance: 21, lengthTolerance: 25 },
            { roundAllowance: 105, length: 101, roundTolerance: 21, lengthTolerance: 25 },
            { roundAllowance: 106, length: 102, roundTolerance: 21, lengthTolerance: 26 }
        ],
        [
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 19, length: 23, roundTolerance: 4, lengthTolerance: 6 },
            { roundAllowance: 20, length: 24, roundTolerance: 4, lengthTolerance: 6 },
            { roundAllowance: 21, length: 25, roundTolerance: 4, lengthTolerance: 6 },
            { roundAllowance: 22, length: 26, roundTolerance: 4, lengthTolerance: 7 },
            { roundAllowance: 23, length: 27, roundTolerance: 5, lengthTolerance: 7 },
            { roundAllowance: 24, length: 28, roundTolerance: 5, lengthTolerance: 7 },
            { roundAllowance: 25, length: 29, roundTolerance: 5, lengthTolerance: 7 },
            { roundAllowance: 26, length: 30, roundTolerance: 5, lengthTolerance: 8 },
            { roundAllowance: 27, length: 31, roundTolerance: 5, lengthTolerance: 8 },
            { roundAllowance: 28, length: 32, roundTolerance: 6, lengthTolerance: 8 },
            { roundAllowance: 29, length: 33, roundTolerance: 6, lengthTolerance: 8 },
            { roundAllowance: 30, length: 34, roundTolerance: 6, lengthTolerance: 9 },
            { roundAllowance: 31, length: 35, roundTolerance: 6, lengthTolerance: 9 },
            { roundAllowance: 32, length: 36, roundTolerance: 6, lengthTolerance: 9 },
            { roundAllowance: 33, length: 37, roundTolerance: 7, lengthTolerance: 9 },
            { roundAllowance: 34, length: 38, roundTolerance: 7, lengthTolerance: 10 },
            { roundAllowance: 35, length: 39, roundTolerance: 7, lengthTolerance: 10 },
            { roundAllowance: 36, length: 40, roundTolerance: 7, lengthTolerance: 10 },
            { roundAllowance: 37, length: 41, roundTolerance: 7, lengthTolerance: 10 },
            { roundAllowance: 38, length: 42, roundTolerance: 8, lengthTolerance: 11 },
            { roundAllowance: 39, length: 43, roundTolerance: 8, lengthTolerance: 11 },
            { roundAllowance: 40, length: 44, roundTolerance: 8, lengthTolerance: 11 },
            { roundAllowance: 41, length: 45, roundTolerance: 8, lengthTolerance: 11 },
            { roundAllowance: 42, length: 46, roundTolerance: 8, lengthTolerance: 12 },
            { roundAllowance: 43, length: 47, roundTolerance: 9, lengthTolerance: 12 },
            { roundAllowance: 44, length: 48, roundTolerance: 9, lengthTolerance: 12 },
            { roundAllowance: 45, length: 49, roundTolerance: 9, lengthTolerance: 12 },
            { roundAllowance: 46, length: 50, roundTolerance: 9, lengthTolerance: 13 },
            { roundAllowance: 47, length: 51, roundTolerance: 9, lengthTolerance: 13 },
            { roundAllowance: 48, length: 52, roundTolerance: 10, lengthTolerance: 13 },
            { roundAllowance: 49, length: 53, roundTolerance: 10, lengthTolerance: 13 },
            { roundAllowance: 50, length: 54, roundTolerance: 10, lengthTolerance: 14 },
            { roundAllowance: 51, length: 55, roundTolerance: 10, lengthTolerance: 14 },
            { roundAllowance: 52, length: 56, roundTolerance: 10, lengthTolerance: 14 },
            { roundAllowance: 53, length: 57, roundTolerance: 11, lengthTolerance: 14 },
            { roundAllowance: 54, length: 58, roundTolerance: 11, lengthTolerance: 15 },
            { roundAllowance: 55, length: 59, roundTolerance: 11, lengthTolerance: 15 },
            { roundAllowance: 56, length: 60, roundTolerance: 11, lengthTolerance: 15 },
            { roundAllowance: 57, length: 61, roundTolerance: 11, lengthTolerance: 15 },
            { roundAllowance: 58, length: 62, roundTolerance: 12, lengthTolerance: 16 },
            { roundAllowance: 59, length: 63, roundTolerance: 12, lengthTolerance: 16 },
            { roundAllowance: 60, length: 64, roundTolerance: 12, lengthTolerance: 16 },
            { roundAllowance: 61, length: 65, roundTolerance: 12, lengthTolerance: 16 },
            { roundAllowance: 62, length: 66, roundTolerance: 12, lengthTolerance: 17 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 },
            { roundAllowance: 0, length: 0, roundTolerance: 0, lengthTolerance: 0 }
        ],
	];

	public findValue(rowValue: number, columnValue: number) {
		const rowIndex = this.findRowIndex(rowValue);
		const columnIndex = this.findColumnIndex(columnValue);

		if (rowIndex === undefined || columnIndex === undefined) {
			return undefined;
		}

		if (
			rowIndex >= 0 &&
			rowIndex < this.grid.length &&
			columnIndex >= 0 &&
			columnIndex < this.grid[rowIndex].length
		) {
			const gridValue = this.grid[rowIndex][columnIndex];
			return gridValue;
		}

		return undefined;
	}

	private findRowIndex(rowValue: number) {
		for (let i = 0; i < this.rowRanges.length; i++) {
			const [min, max] = this.rowRanges[i];
			if (rowValue >= min && rowValue <= max) {
				return i;
			}
		}

		return undefined;
	}

	private findColumnIndex(columnValue: number) {
		for (let i = 0; i < this.columnRanges.length; i++) {
			const [min, max] = this.columnRanges[i];
			if (columnValue >= min && columnValue <= max) {
				return i;
			}
		}

		return undefined;
	}
}