<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('specifications', function (Blueprint $table) {
            $table->dropForeign('specifications_norm_id_foreign');
            $table->dropForeign('specifications_customer_id_foreign');
            $table->dropColumn([
                'norm_id',
                'specification_note',
                'note',
                'customer_id',
                'bom',
                'is_electric_steel',
                'is_vacuum_degassed',
                'is_classified_steel_plant',
                'is_casting_beam_shielded',
                'is_deoxidized',
                'is_killed_steel',
                'jominy_batch',
                'continuous_casting',
                'ingot_casting',
                'deformation',
                'stretch_forging_degree',
                'check_stock',
                'KSR_max',
                'attestation',
                'attestation_entity',
                'non_destructive_testing',
                'frequency',
                'specimen_material',
                'specimen_rest_material',
                'WZV_temperature',
                'zug',
                'kbz',
                'wzv',
                'needs_jominy_face_quenching_test',
                'needs_ic_3651_2_method_a',
                'needs_ic_3651_1',
                'needs_ic_a262_practice_e',
                'product_analysis',
                'needs_microsection_structure',
                'needs_microsection_grain_size',
                'needs_microsection_carburized',
                'needs_microsection_cleanliness',
                'grain_size',
                'is_50601',
                'astm_e112',
                'iso_643',
                'grain_size_after_carburizing',
                'cleanliness_50602',
                'k4',
                'k3',
                'k2',
                'cleanliness_4967',
                'a_fine',
                'a_coarse',
                'b_fine',
                'b_coarse',
                'c_fine',
                'c_coarse',
                'd_fine',
                'd_coarse',
                'ds',
                'microstructure_assessment',
                'image',
                'microstructure_quota',
                'microstructure_max_quota',
                'work_sequence_text_field',
                'work_instruction',
                'grain_size_text_field',
                'cleanliness_astm_e_45',
                'cleanliness_nfa_04_106',
                'cleanliness_text_field',
                'microstructure_text_field',
                'ultrasound_norm_1',
                'ultrasound_output_1',
                'ultrasound_scope_inspection_1',
                'ultrasound_testing_area_1',
                'ultrasound_efg_max_1',
                'ultrasound_test_duration_1',
                'ultrasound_norm_2',
                'ultrasound_output_2',
                'ultrasound_scope_inspection_2',
                'ultrasound_testing_area_2',
                'ultrasound_efg_max_2',
                'ultrasound_test_duration_2',
                'ultrasound_norm_3',
                'ultrasound_output_3',
                'ultrasound_scope_inspection_3',
                'ultrasound_testing_area_3',
                'ultrasound_efg_max_3',
                'ultrasound_test_duration_3',
                'ultrasound_text_field',
                'residual_magnetic_field_strength',
                'mt_norm_1',
                'mt_output_1',
                'mt_test_criteria_1',
                'mt_scope_inspection_1',
                'mt_test_duration_1',
                'mt_norm_2',
                'mt_output_2',
                'mt_test_criteria_2',
                'mt_scope_inspection_2',
                'mt_test_duration_2',
                'mt_norm_3',
                'mt_output_3',
                'mt_test_criteria_3',
                'mt_scope_inspection_3',
                'mt_test_duration_3',
                'mt_text_field',
                'pt_norm_1',
                'pt_output_1',
                'pt_test_criteria_1',
                'pt_scope_inspection_1',
                'pt_test_duration_1',
                'pt_norm_2',
                'pt_output_2',
                'pt_test_criteria_2',
                'pt_scope_inspection_2',
                'pt_test_duration_2',
                'pt_norm_3',
                'pt_output_3',
                'pt_test_criteria_3',
                'pt_scope_inspection_3',
                'pt_test_duration_3',
                'pt_text_field',
                'vt_output_1',
                'vt_test_criteria_1',
                'vt_scope_inspection_1',
                'vt_test_duration_1',
                'vt_text_field',
                'deviations_customer',
                'deviations_customer_confirmation_1',
                'deviations_customer_confirmation_2',
                'deviations_customer_confirmation_3'
            ]);
            $table->string('name')->nullable();
            $table->foreignId('documentation_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('metallography_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('testing_scope_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('non_destructive_testing_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('us_norm_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('mt_norm_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('pt_norm_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('vt_norm_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('residual_material_id')->nullable()->constrained()->nullOnDelete();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('specifications', function (Blueprint $table) {
            $table->dropColumn('name');
            $table->dropForeign('specifications_documentation_id_foreign');
            $table->dropColumn('documentation_id');
            $table->dropForeign('specifications_metallography_id_foreign');
            $table->dropColumn('metallography_id');
            $table->dropForeign('specifications_testing_scope_id_foreign');
            $table->dropColumn('testing_scope_id');
            $table->dropForeign('specifications_non_destructive_testing_id_foreign');
            $table->dropColumn('non_destructive_testing_id');
            $table->dropForeign('specifications_us_norm_id_foreign');
            $table->dropColumn('us_norm_id');
            $table->dropForeign('specifications_mt_norm_id_foreign');
            $table->dropColumn('mt_norm_id');
            $table->dropForeign('specifications_pt_norm_id_foreign');
            $table->dropColumn('pt_norm_id');
            $table->dropForeign('specifications_vt_norm_id_foreign');
            $table->dropColumn('vt_norm_id');
            $table->dropForeign('specifications_residual_material_id_foreign');
            $table->dropColumn('residual_material_id');

            $table->foreignId('norm_id')->nullable()->constrained()->nullOnDelete();
            $table->string('specification_note')->nullable();
            $table->longText('note')->nullable();
            $table->foreignId('customer_id')->nullable()->constrained()->nullOnDelete();
            $table->string('bom')->nullable();
            $table->boolean('is_electric_steel')->default(false);
            $table->boolean('is_vacuum_degassed')->default(false);
            $table->boolean('is_classified_steel_plant')->default(false);
            $table->boolean('is_casting_beam_shielded')->default(false);
            $table->boolean('is_deoxidized')->default(false);
            $table->boolean('is_killed_steel')->default(false);
            $table->string('jominy_batch')->nullable();
            $table->string('continuous_casting')->nullable();
            $table->string('ingot_casting')->nullable();
            $table->string('deformation')->nullable();
            $table->string('stretch_forging_degree')->nullable();
            $table->boolean('check_stock')->default(false);
            $table->string('KSR_max')->nullable();
            $table->string('attestation')->nullable();
            $table->string('attestation_entity')->nullable();
            $table->string('non_destructive_testing')->nullable();
            $table->string('frequency')->nullable();
            $table->string('specimen_material')->nullable();
            $table->string('specimen_rest_material')->nullable();
            $table->integer('WZV_temperature')->nullable();
            $table->double('zug')->nullable();
            $table->double('kbz')->nullable();
            $table->double('wzv')->nullable();
            $table->boolean('needs_jominy_face_quenching_test')->default(false);
            $table->boolean('needs_ic_3651_2_method_a')->default(false);
            $table->boolean('needs_ic_3651_1')->default(false);
            $table->boolean('needs_ic_a262_practice_e')->default(false);
            $table->boolean('product_analysis')->default(false);
            $table->boolean('needs_microsection_structure')->default(false);
            $table->boolean('needs_microsection_grain_size')->default(false);
            $table->boolean('needs_microsection_carburized')->default(false);
            $table->boolean('needs_microsection_cleanliness')->default(false);
            $table->string('grain_size')->nullable();
            $table->boolean('is_50601')->default(false);
            $table->boolean('astm_e112')->default(false);
            $table->boolean('iso_643')->default(false);
            $table->string('grain_size_after_carburizing')->nullable();
            $table->string('cleanliness_50602')->nullable();
            $table->integer('k4')->nullable();
            $table->integer('k3')->nullable();
            $table->integer('k2')->nullable();
            $table->string('cleanliness_4967')->nullable();
            $table->double('a_fine')->nullable();
            $table->double('a_coarse')->nullable();
            $table->double('b_fine')->nullable();
            $table->double('b_coarse')->nullable();
            $table->double('c_fine')->nullable();
            $table->double('c_coarse')->nullable();
            $table->double('d_fine')->nullable();
            $table->double('d_coarse')->nullable();
            $table->double('ds')->nullable();
            $table->string('microstructure_assessment')->nullable();
            $table->boolean('image')->default(0);
            $table->string('microstructure_quota')->nullable();
            $table->integer('microstructure_max_quota')->nullable();
            $table->string('work_sequence_text_field',100)->nullable();
            $table->string('work_instruction',100)->nullable();
            $table->string('grain_size_text_field',100)->nullable();
            $table->boolean('cleanliness_astm_e_45')->default(false);
            $table->boolean('cleanliness_nfa_04_106')->default(false);
            $table->string('cleanliness_text_field',100)->nullable();
            $table->string('microstructure_text_field',100)->nullable();
            $table->string('ultrasound_norm_1',100)->nullable();
            $table->string('ultrasound_output_1',100)->nullable();
            $table->string('ultrasound_scope_inspection_1',100)->nullable();
            $table->string('ultrasound_testing_area_1',100)->nullable();
            $table->double('ultrasound_efg_max_1')->nullable();
            $table->double('ultrasound_test_duration_1')->nullable();
            $table->string('ultrasound_norm_2',100)->nullable();
            $table->string('ultrasound_output_2',100)->nullable();
            $table->string('ultrasound_scope_inspection_2',100)->nullable();
            $table->string('ultrasound_testing_area_2',100)->nullable();
            $table->double('ultrasound_efg_max_2')->nullable();
            $table->double('ultrasound_test_duration_2')->nullable();
            $table->string('ultrasound_norm_3',100)->nullable();
            $table->string('ultrasound_output_3',100)->nullable();
            $table->string('ultrasound_scope_inspection_3',100)->nullable();
            $table->string('ultrasound_testing_area_3',100)->nullable();
            $table->double('ultrasound_efg_max_3')->nullable();
            $table->double('ultrasound_test_duration_3')->nullable();
            $table->string('ultrasound_text_field',100)->nullable();
            $table->string('residual_magnetic_field_strength',100)->nullable();
            $table->string('mt_norm_1',100)->nullable();
            $table->string('mt_output_1',100)->nullable();
            $table->string('mt_test_criteria_1',100)->nullable();
            $table->string('mt_scope_inspection_1',100)->nullable();
            $table->double('mt_test_duration_1')->nullable();
            $table->string('mt_norm_2',100)->nullable();
            $table->string('mt_output_2',100)->nullable();
            $table->string('mt_test_criteria_2',100)->nullable();
            $table->string('mt_scope_inspection_2',100)->nullable();
            $table->double('mt_test_duration_2')->nullable();
            $table->string('mt_norm_3',100)->nullable();
            $table->string('mt_output_3',100)->nullable();
            $table->string('mt_test_criteria_3',100)->nullable();
            $table->string('mt_scope_inspection_3',100)->nullable();
            $table->double('mt_test_duration_3')->nullable();
            $table->string('mt_text_field',100)->nullable();
            $table->string('pt_norm_1',100)->nullable();
            $table->string('pt_output_1',100)->nullable();
            $table->string('pt_test_criteria_1',100)->nullable();
            $table->string('pt_scope_inspection_1',100)->nullable();
            $table->double('pt_test_duration_1')->nullable();
            $table->string('pt_norm_2',100,100)->nullable();
            $table->string('pt_output_2',100)->nullable();
            $table->string('pt_test_criteria_2',100)->nullable();
            $table->string('pt_scope_inspection_2',100)->nullable();
            $table->double('pt_test_duration_2')->nullable();
            $table->string('pt_norm_3',100)->nullable();
            $table->string('pt_output_3',100)->nullable();
            $table->string('pt_test_criteria_3',100)->nullable();
            $table->string('pt_scope_inspection_3',100)->nullable();
            $table->double('pt_test_duration_3')->nullable();
            $table->string('pt_text_field',100)->nullable();
            $table->string('vt_output_1',100)->nullable();
            $table->string('vt_test_criteria_1',100)->nullable();
            $table->string('vt_scope_inspection_1',100)->nullable();
            $table->double('vt_test_duration_1')->nullable();
            $table->string('vt_text_field',100)->nullable();
            $table->string('deviations_customer',100)->nullable();
            $table->boolean('deviations_customer_confirmation_1')->default(false);
            $table->boolean('deviations_customer_confirmation_2')->default(false);
            $table->boolean('deviations_customer_confirmation_3')->default(false);
        });
    }
};
