export enum QuantityErrorType {
    DUPLICATE_SERIAL = "DUPLICATE_SERIAL",
    SERIAL_REQUIRED_FOR_FINAL_ITEM = "SERIAL_REQUIRED_FOR_FINAL_ITEM",
    BATCH_REQUIRED_FOR_FINAL_ITEM = "BATCH_REQUIRED_FOR_FINAL_ITEM",
    SERIAL_REQUIRED_FOR_COMPONENT = "SERIAL_REQUIRED_FOR_COMPONENT",
    BATCH_REQUIRED_FOR_COMPONENT = "BATCH_REQUIRED_FOR_COMPONENT",
    PACKAGING_INSTRUCTION_FOR_HU = "PACKAGING_INSTRUCTION_FOR_HU",
    QUANTITY_IN_HU_EXCEEDS_FOR_PI = "QUANTITY_IN_HU_EXCEEDS_FOR_PI",
}
