export enum MPCostSubGroup {
    MATERIAL_INTERNAL = 'MATERIAL_INTERNAL',
    MATERIAL_ACQUIRED = 'MATERIAL_ACQUIRED',
    INTERNAL_TECH_OFFICE = 'INTERNAL_TECH_OFFICE',
    INTERNAL_MACHINING = 'INTERNAL_MACHINING',
    INTERNAL_EROSION = 'INTERNAL_EROSION',
    INTERNAL_ASSEMBLY = 'INTERNAL_ASSEMBLY',
    INTERNAL_SAMPLING = 'INTERNAL_SAMPLING',
    INTERNAL_QUALITY = 'INTERNAL_QUALITY',
    EXTERNAL = 'EXTERNAL'
}