

export enum PermissionEnum {
    BASEVISU_VIEW = 'BASEVISU_VIEW',

    BASEVISU_MACHINES_EDIT = 'BASEVISU_MACHINES_EDIT',
    BASEVISU_MACHINES_VIEW = 'BASEVISU_MACHINES_VIEW',



    BASEVISU_MACHINE_GROUPS_EDIT = 'BASEVISU_MACHINE_GROUPS_EDIT',
    BASEVISU_MACHINE_GROUPS_VIEW = 'BASEVISU_MACHINE_GROUPS_VIEW',

    BASEVISU_TPM_GROUPS_EDIT = 'BASEVISU_TPM_GROUPS_EDIT',
    BASEVISU_TPM_GROUPS_VIEW = 'BASEVISU_TPM_GROUPS_VIEW',

    BASEVISU_TPM_SUB_GROUPS_EDIT = 'BASEVISU_TPM_SUB_GROUPS_EDIT',
    BASEVISU_TPM_SUB_GROUPS_VIEW = 'BASEVISU_TPM_SUB_GROUPS_VIEW',

    BASEVISU_MACHINE_STATES_EDIT = 'BASEVISU_MACHINE_STATES_EDIT',
    BASEVISU_MACHINE_STATES_VIEW = 'BASEVISU_MACHINE_STATES_VIEW',

    BASEVISU_BAD_PART_REASONS_EDIT = 'BASEVISU_BAD_PART_REASONS_EDIT',
    BASEVISU_BAD_PART_REASONS_VIEW = 'BASEVISU_BAD_PART_REASONS_VIEW',

    BASEVISU_ITEMS_EDIT = 'BASEVISU_ITEMS_EDIT',
    BASEVISU_ITEMS_VIEW = 'BASEVISU_ITEMS_VIEW',

    BASEVISU_ITEM_GROUPS_EDIT = 'BASEVISU_ITEM_GROUPS_EDIT',
    BASEVISU_ITEM_GROUPS_VIEW = 'BASEVISU_ITEM_GROUPS_VIEW',

    BASEVISU_TOOLS_EDIT = 'BASEVISU_TOOLS_EDIT',
    BASEVISU_TOOLS_VIEW = 'BASEVISU_TOOLS_VIEW',

    BASEVISU_USERS_EDIT = 'BASEVISU_USERS_EDIT',
    BASEVISU_USERS_VIEW = 'BASEVISU_USERS_VIEW',

    BASEVISU_USER_GROUPS_EDIT = 'BASEVISU_USER_GROUPS_EDIT',
    BASEVISU_USER_GROUPS_VIEW = 'BASEVISU_USER_GROUPS_VIEW',

    BASEVISU_QUALIFICATIONS_EDIT = 'BASEVISU_QUALIFICATIONS_EDIT',
    BASEVISU_QUALIFICATIONS_VIEW = 'BASEVISU_QUALIFICATIONS_VIEW',

    BASEVISU_HALLS_EDIT = 'BASEVISU_HALLS_EDIT',
    BASEVISU_HALLS_VIEW = 'BASEVISU_HALLS_VIEW',

    BASEVISU_CUSTOMERS_EDIT = 'BASEVISU_CUSTOMERS_EDIT',
    BASEVISU_CUSTOMERS_VIEW = 'BASEVISU_CUSTOMERS_VIEW',

    BASEVISU_CUSTOMER_GROUPS_EDIT = 'BASEVISU_CUSTOMER_GROUPS_EDIT',
    BASEVISU_CUSTOMER_GROUPS_VIEW = 'BASEVISU_CUSTOMER_GROUPS_VIEW',

    BASEVISU_SALES_GROUPS_EDIT = 'BASEVISU_SALES_GROUPS_EDIT',
    BASEVISU_SALES_GROUPS_VIEW = 'BASEVISU_SALES_GROUPS_VIEW',

    BASEVISU_SUPPLIERS_EDIT = 'BASEVISU_SUPPLIERS_EDIT',
    BASEVISU_SUPPLIERS_VIEW = 'BASEVISU_SUPPLIERS_VIEW',

    BASEVISU_ENERGY_GATEWAYS_EDIT = 'BASEVISU_ENERGY_GATEWAYS_EDIT',
    BASEVISU_ENERGY_GATEWAYS_VIEW = 'BASEVISU_ENERGY_GATEWAYS_VIEW',

    BASEVISU_ENERGY_CONSUMERS_EDIT = 'BASEVISU_ENERGY_CONSUMERS_EDIT',
    BASEVISU_ENERGY_CONSUMERS_VIEW = 'BASEVISU_ENERGY_CONSUMERS_VIEW',

    BASEVISU_ENERGY_CONSUMER_GROUPS_EDIT = 'BASEVISU_ENERGY_CONSUMER_GROUPS_EDIT',
    BASEVISU_ENERGY_CONSUMER_GROUPS_VIEW = 'BASEVISU_ENERGY_CONSUMER_GROUPS_VIEW',

    BASEVISU_CRUCIBLES_EDIT = 'BASEVISU_CRUCIBLES_EDIT',
    BASEVISU_CRUCIBLES_VIEW = 'BASEVISU_CRUCIBLES_VIEW',
    
    BASEVISU_PRINTERS_VIEW = "BASEVISU_PRINTERS_VIEW",
    BASEVISU_PRINTERS_EDIT = "BASEVISU_PRINTERS_EDIT",

    BASEVISU_TERMINALS_VIEW = "BASEVISU_TERMINALS_VIEW",
    BASEVISU_TERMINALS_EDIT = "BASEVISU_TERMINALS_EDIT",
    
    BASEVISU_CAPACITIES_EDIT = 'BASEVISU_CAPACITIES_EDIT',
    BASEVISU_CAPACITIES_VIEW = 'BASEVISU_CAPACITIES_VIEW',

    BASEVISU_SHIFT_MODELS_EDIT = 'BASEVISU_SHIFT_MODELS_EDIT',
    BASEVISU_SHIFT_MODELS_VIEW = 'BASEVISU_SHIFT_MODELS_VIEW',

    BASEVISU_SETTINGS_EDIT = 'BASEVISU_SETTINGS_EDIT',
    BASEVISU_SETTINGS_VIEW = 'BASEVISU_SETTINGS_VIEW',

    BASEVISU_ROLES_EDIT = 'BASEVISU_ROLES_EDIT',
    BASEVISU_ROLES_VIEW = 'BASEVISU_ROLES_VIEW',

    BASEVISU_PERMISSIONS_VIEW = 'BASEVISU_PERMISSIONS_VIEW',

    HWEKALK_SALES_OPPORTUNITIES_VIEW = 'HWEKALK_SALES_OPPORTUNITIES_VIEW',
    HWEKALK_SALES_OPPORTUNITIES_DELETE = 'HWEKALK_SALES_OPPORTUNITIES_DELETE',
    HWEKALK_SALES_OPPORTUNITIES_IMPORT = 'HWEKALK_SALES_OPPORTUNITIES_IMPORT',
    HWEKALK_SALES_OPPORTUNITIES_CREATE_OFFER = 'HWEKALK_SALES_OPPORTUNITIES_CREATE_OFFER',
    HWEKALK_OFFER_POS_VIEW = 'HWEKALK_OFFER_POS_VIEW',
    HWEKALK_OFFER_POS_EDIT = 'HWEKALK_OFFER_POS_EDIT',
    HWEKALK_OFFER_POS_CREATE = 'HWEKALK_OFFER_POS_CREATE',
    HWEKALK_OFFER_POS_DELETE = 'HWEKALK_OFFER_POS_DELETE',
    HWEKALK_OFFER_POS_COPY = 'HWEKALK_OFFER_POS_COPY',
    HWEKALK_OFFER_POS_COPY_OFFER_ASSESSMENT_BUTTON_VIEW = 'HWEKALK_OFFER_POS_COPY_OFFER_ASSESSMENT_BUTTON_VIEW',
    HWEKALK_OFFER_POS_COPY_OFFER_POS_BUTTON_VIEW = 'HWEKALK_OFFER_POS_COPY_OFFER_POS_BUTTON_VIEW',
    HWEKALK_SALES_VIEW = 'HWEKALK_SALES_VIEW',
    HWEKALK_SALES_COSTS_VIEW = 'HWEKALK_SALES_COSTS_VIEW',
    HWEKALK_SALES_COSTS_GENERATE = 'HWEKALK_SALES_COSTS_GENERATE',
    HWEKALK_SALES_COSTS_NEW = 'HWEKALK_SALES_COSTS_NEW',
    HWEKALK_SALES_COSTS_DELETE = 'HWEKALK_SALES_COSTS_DELETE',
    HWEKALK_OFFER_POS_DOWNLOAD = 'HWEKALK_OFFER_POS_DOWNLOAD',

    HWEKALK_OFFER_VIEW = 'HWEKALK_OFFER_VIEW',
    HWEKALK_TECHINCAL_ASSESSMENT_VIEW = 'HWEKALK_TECHINCAL_ASSESSMENT_VIEW',
    HWEKALK_CALC_VIEW = 'HWEKALK_CALC_VIEW',
    HWEKALK_CALC_BUTTON_VIEW = 'HWEKALK_CALC_BUTTON_VIEW',
    HWEKALK_CALC_MECHANIC_VIEW = 'HWEKALK_CALC_MECHANIC_VIEW',
    HWEKALK_OBTAIN_EXTERNAL_VIEW = 'HWEKALK_OBTAIN_EXTERNAL_VIEW',
    HWEKALK_QUOTATION_CREATION_VIEW = 'HWEKALK_QUOTATION_CREATION_VIEW',
    HWEKALK_OFFER_CREATE = 'HWEKALK_OFFER_CREATE',
    HWEKALK_OFFER_EDIT = 'HWEKALK_OFFER_EDIT',
    HWEKALK_OFFER_DELETE = 'HWEKALK_OFFER_DELETE',
    HWEKALK_OFFER_ARCHIVED_BUTTON_VIEW = 'HWEKALK_OFFER_ARCHIVED_BUTTON_VIEW',
    HWEKALK_OFFER_SEARCH_INPUT_VIEW = 'HWEKALK_OFFER_SEARCH_INPUT_VIEW',
    HWEKALK_ASSESSMENT_INFO_BUTTON_VIEW = 'HWEKALK_ASSESSMENT_INFO_BUTTON_VIEW',
    HWEKALK_ASSESSMENT_CHANGE_BUTTON_VIEW = 'HWEKALK_ASSESSMENT_CHANGE_BUTTON_VIEW',
    HWEKALK_ASSESSMENT_EDIT_VIEW = 'HWEKALK_ASSESSMENT_EDIT_VIEW',
    HWEKALK_ASSESSMENT_READ_ONLY = 'HWEKALK_ASSESSMENT_READ_ONLY',
    HWEKALK_INDIVIDUAL_ASSESSMENT_READ_ONLY = 'HWEKALK_INDIVIDUAL_ASSESSMENT_READ_ONLY',
    HWEKALK_INDIVIDUAL_ASSESSMENT_EDIT = 'HWEKALK_INDIVIDUAL_ASSESSMENT_EDIT',
    HWEKALK_HEAT_TREATMENT_READ_ONLY = 'HWEKALK_HEAT_TREATMENT_READ_ONLY',
    HWEKALK_HEAT_TREATMENT_EDIT = 'HWEKALK_HEAT_TREATMENT_EDIT',
    HWEKALK_CUSTOMER_REQUEST_READ_ONLY = 'HWEKALK_CUSTOMER_REQUEST_READ_ONLY',
    HWEKALK_CUSTOMER_REQUEST_EDIT = 'HWEKALK_CUSTOMER_REQUEST_EDIT',
    HWEKALK_DIMENSION_READ_ONLY = 'HWEKALK_DIMENSION_READ_ONLY',
    HWEKALK_DIMENSION_EDIT = 'HWEKALK_DIMENSION_EDIT',
    HWEKALK_WORK_PLAN_READ_ONLY = 'HWEKALK_WORK_PLAN_READ_ONLY',
    HWEKALK_WORK_PLAN_EDIT = 'HWEKALK_WORK_PLAN_EDIT',
    HWEKALK_WORK_PLAN_DELETE_BUTTON_VIEW = 'HWEKALK_WORK_PLAN_DELETE_BUTTON_VIEW',
    HWEKALK_WORK_PLAN_GENERATE_BUTTON_VIEW = 'HWEKALK_WORK_PLAN_GENERATE_BUTTON_VIEW',
    HWEKALK_WORK_PLAN_NEW_BUTTON_VIEW = 'HWEKALK_WORK_PLAN_NEW_BUTTON_VIEW',
    HWEKALK_WORK_PLAN_GRID_DELETE_BUTTON_VIEW = 'HWEKALK_WORK_PLAN_GRID_DELETE_BUTTON_VIEW',
    HWEKALK_SALES_ACTION = 'HWEKALK_SALES_ACTION',
    HWEKALK_SUMMARY_VIEW = 'HWEKALK_SUMMARY_VIEW',
    HWEKALK_OFFER_CRM_UPLOAD = 'HWEKALK_OFFER_CRM_UPLOAD',
    HWEKALK_SALES_EDIT = 'HWEKALK_SALES_EDIT',
    HWEKALK_OFFER_LOG_VIEW = 'HWEKALK_OFFER_LOG_VIEW',
    HWEKALK_SPECIFICATIONS_EDIT = 'HWEKALK_SPECIFICATIONS_EDIT',
    HWEKALK_EVALUATION_VIEW = 'HWEKALK_EVALUATION_VIEW',
    HWEKALK_MATERIALS_EDIT = 'HWEKALK_MATERIALS_EDIT',
    HWEKALK_CLIENT_ORDER_VIEW = 'HWEKALK_CLIENT_ORDER_VIEW',
    HWEKALK_CLIENT_ORDER_RELEASED_EDIT = 'HWEKALK_CLIENT_ORDER_RELEASED_EDIT',
    HWEKALK_CLIENT_ORDER_HEAT_TREATMENTS_EDIT = 'HWEKALK_CLIENT_ORDER_HEAT_TREATMENTS_EDIT',
    HWEKALK_COSTS_EDIT = 'HWEKALK_COSTS_EDIT',
    HWEKALK_MATERIAL_DATABASES_EDIT = 'HWEKALK_MATERIAL_DATABASES_EDIT',
    STATUSBOARD_VIEW = 'STATUSBOARD_VIEW',

}
export class PermissionEnumClass {

}
