<?php

namespace App\Enums;

enum ProdInspectionOperationFrequency: string
{
    case COMPONENT_SCANNED = 'COMPONENT_SCANNED';
    case OPERATION_IN_SETUP = 'OPERATION_IN_SETUP';
    case OPERATION_IN_PRODUCTION = 'OPERATION_IN_PRODUCTION';
    case OPERATION_CLOSED = 'OPERATION_CLOSED';
    case MACHINE_STATE_QUALITY_RELEVANT = 'MACHINE_STATE_QUALITY_RELEVANT';
    case CYCLE_FREQUENCY = 'CYCLE_FREQUENCY';
    case MACHINE_SHIFT = 'MACHINE_SHIFT';
    case HANDLING_UNIT_CREATED = 'HANDLING_UNIT_CREATED';
    case TIME_FREQUENCY = 'TIME_FREQUENCY';
}
