<?php

namespace App\Enums;

enum QualiEventType: string
{
    case COMPONENT_SCANNED = 'COMPONENT_SCANNED';
    case OPERATION_SETUP_STARTED = 'OPERATION_SETUP_STARTED';
    case OPERATION_PRODUCTION_STARTED = 'OPERATION_PRODUCTION_STARTED';
    case OPERATION_CLOSED = 'OPERATION_CLOSED';
    case HANDLING_UNIT_CREATED = 'HANDLING_UNIT_CREATED';
    case MACHINE_STATE_QUALITY_RELEVANT = 'MACHINE_STATE_QUALITY_RELEVANT';
}
