<?php

namespace App\Enums;

enum QuantityErrorType: string
{
    case DUPLICATE_SERIAL = 'DUPLICATE_SERIAL';
    case SERIAL_REQUIRED_FOR_FINAL_ITEM = 'SERIAL_REQUIRED_FOR_FINAL_ITEM';
    case BATCH_REQUIRED_FOR_FINAL_ITEM = 'BATCH_REQUIRED_FOR_FINAL_ITEM';
    case SERIAL_REQUIRED_FOR_COMPONENT = 'SERIAL_REQUIRED_FOR_COMPONENT';
    case BATCH_REQUIRED_FOR_COMPONENT = 'BATCH_REQUIRED_FOR_COMPONENT';
    case PACKAGING_INSTRUCTION_FOR_HU = 'PACKAGING_INSTRUCTION_FOR_HU';
    case QUANTITY_IN_HU_EXCEEDS_FOR_PI = 'QUANTITY_IN_HU_EXCEEDS_FOR_PI';
}