<?php

namespace App\Providers;

use App\Models\Area;
use App\Models\CalculationDeformation;
use App\Models\CalculationDocumentation;
use App\Models\CalculationDocumentationCertificate;
use App\Models\CalculationResidualMaterial;
use App\Models\CalculationNonDestructiveTesting;
use App\Models\CalculationNonDestructiveTestingAttestationEntity;
use App\Models\CalculationMetallography;
use App\Models\CalculationTestingScope;
use App\Models\CalculationTestingScopeAccordingToImpactTest;
use App\Models\CalculationTestingScopeAccordingToTensileTest;
use App\Models\CalculationTestingScopeAttestationEntity;
use App\Models\CalculationTestingScopeClassifiedBy;
use App\Models\CalculationTestingScopeMeltingType;
use App\Models\CalculationTestingScopeSampleDepth;
use App\Models\Chat;
use App\Models\Classification;
use App\Models\Contact;
use App\Models\ContactableContact;
use App\Models\CrmAction;
use App\Models\CustomerCrmActionLog;
use App\Models\CustomerMarketSegment;
use App\Models\Deformation;
use App\Models\EightDReport;
use App\Models\EightDReportAction;
use App\Models\EightDReportFiveWhy;
use App\Models\EightDReportIshikawa;
use App\Models\EightDReportTeam;
use App\Models\EmployeeClassification;
use App\Models\HallCapacitySetting;
use App\Models\HandlingUnit;
use App\Models\HardenabilityRange;
use App\Models\HweCertificate;
use App\Models\HweCertificateHweQsSample;
use App\Models\HweFreightCost;
use App\Models\HweHeatTreatmentCost;
use App\Models\HweMeltAnalysis;
use App\Models\HweMeltType;
use App\Models\HweWorkPlan;
use App\Models\HweWorkPlanAdditionalHeatTreatment;
use App\Models\HweWorkPlanHeatTreatment;
use App\Models\ItemType;
use App\Models\MachineClassification;
use App\Models\MachineProdOrderPosOperationTime;
use App\Models\MarketSegment;
use App\Models\MaterialAnalysis;
use App\Models\Message;
use App\Models\OperationPlanPosHeatTreatment;
use App\Models\MachineState;
use App\Models\MachineStateGroup;
use App\Models\PotentialClassification;
use App\Models\ProdInspectionOperation;
use App\Models\ProdLot;
use App\Models\ProdOrderPos;
use App\Models\ProdOrderPosOperation;
use App\Models\ProdOrderPosOperationBatch;
use App\Models\ProdOrderPosOperationDelivery;
use App\Models\ProductionSupplyArea;
use App\Models\RevenueClassification;
use App\Models\SalesStatus;
use App\Models\StorageBin;
use App\Models\StorageLocation;
use App\Models\StorageSection;
use App\Models\StorageType;
use App\Models\TestingScopeSampleDepth;
use App\Models\TransportOrder;
use App\Models\TransportOrderPos;
use App\Models\TransportOrderType;
use App\Models\UsNormAdjustment;
use App\Models\VisibilitySetting;
use App\Models\AbsenceRequest;
use App\Models\AbsenceType;
use App\Models\BacklogItemWeek;
use App\Models\Bom;
use App\Models\BomPos;
use App\Models\ItemState;
use App\Models\ItemStateGroup;
use App\Models\ItemPlant;
use App\Models\Calculation;
use App\Models\CalculationHeatTreatment;
use App\Models\CalculationAdditionalHeatTreatment;
use App\Models\CalculationChemAnalysis;
use App\Models\CalculationHardenabilityRange;
use App\Models\CalculationMaterialAnalysis;
use App\Models\CallOffSimulation;
use App\Models\Capacity;
use App\Models\Country;
use App\Models\Crucible;
use App\Models\Customer;
use App\Models\DeliveryTerm;
use App\Models\Documentation;
use App\Models\DocumentationCertificate;
use App\Models\EnergyConsumer;
use App\Models\EnergyConsumerMachine;
use App\Models\EnergyConsumption;
use App\Models\EnergyGateway;
use App\Models\EnergyMeter;
use App\Models\EnergyMeterReading;
use App\Models\Equipment;
use App\Models\Hall;
use App\Models\HweAdditionalCostTrigger;
use App\Models\HweKalkLog;
use App\Models\HweQsCleanlinessTest;
use App\Models\HweQsGrainSizeTest;
use App\Models\HweQsHb;
use App\Models\HweQsHbPos;
use App\Models\HweQsImpactTest;
use App\Models\HweQsImpactTestPos;
use App\Models\HweQsJominyTest;
use App\Models\HweQsMtNorm;
use App\Models\HweQsPtNorm;
use App\Models\HweQsTensileTest;
use App\Models\HweQsUsNorm;
use App\Models\HweQsUsNormAdjustment;
use App\Models\HweQsUsNormRating;
use App\Models\HweQsUsNormTestScope;
use App\Models\HweQsUsNormTestSection;
use App\Models\HweQsVtNorm;
use App\Models\HweRingRollingFactor;
use App\Models\Item;
use App\Models\Machine;
use App\Models\MachineGroup;
use App\Models\Material;
use App\Models\MaterialConsumption;
use App\Models\MaterialDatabase;
use App\Models\Metallography;
use App\Models\MpCost;
use App\Models\MpCostMachine;
use App\Models\MpMaterial;
use App\Models\MpOfferPos;
use App\Models\MpOffer;
use App\Models\MpPersonnel;
use App\Models\MtNorm;
use App\Models\MtNormControlUnit;
use App\Models\MtSpec;
use App\Models\NonDestructiveTesting;
use App\Models\NonDestructiveTestingAttestationEntity;
use App\Models\Norm;
use App\Models\Offer;
use App\Models\OfferPos;
use App\Models\OfferPosCost;
use App\Models\OfferPosDimensionShaftUpsetPart;
use App\Models\OfferPosDimensionUpsetPartForgedBeam;
use App\Models\OfferPosMechanicalProcess;
use App\Models\OfferPosRawDimension;
use App\Models\OperationPlan;
use App\Models\OperationPlanPos;
use App\Models\OperationControlProfile;
use App\Models\PaymentTerm;
use App\Models\ProdOrder;
use App\Models\PtNorm;
use App\Models\RawDimensionType;
use App\Models\ResidualMaterial;
use App\Models\SalesOpportunity;
use App\Models\SequenceOperation;
use App\Models\SerialNumberProfile;
use App\Models\Shift;
use App\Models\ShiftModel;
use App\Models\ShiftModelShift;
use App\Models\Specification;
use App\Models\Supplier;
use App\Models\TestingScope;
use App\Models\TestingScopeAccordingToImpactTest;
use App\Models\TestingScopeAccordingToTensileTest;
use App\Models\TestingScopeAttestationEntity;
use App\Models\User;
use App\Models\UsNorm;
use App\Models\Department;
use App\Models\ItemStateMachine;
use App\Models\UsNormRating;
use App\Models\UsNormTestScope;
use App\Models\UsNormTestSection;
use App\Models\VtNorm;
use App\Models\VtNormTestTechnique;
use App\Models\VtNormAuxiliaryMean;
use App\Models\Warehouse;
use App\Models\HwePackagingCost;
use App\Models\HwePackagingCostProductType;
use App\Models\HweQsSample;
use App\Models\HweQsSamplesProdOrderPos;
use App\Models\HweOfferPosWorkPlanLeadTime;
use App\Models\MarkerRecipe;
use App\Models\MarkerRecipePos;
use App\Models\MarkerRecipePosBlock;
use App\Models\HweAdditionalCost;
use App\Models\UnitOfMeasure;
use App\Models\HweHeatTreatmentFactor;
use App\Models\NotificationGroup;
use App\Models\NotificationGroupEmailAddress;
use App\Models\NotificationGroupNotificationType;
use App\Models\NotificationGroupUser;
use App\Models\Setting;
use App\Models\Language;
use App\Models\Printer;
use App\Models\ProdOrderPosOperationQuantity;
use App\Models\Terminal;
use App\Models\PackagingInstruction;
use App\Models\PackagingInstructionPos;
use App\Models\ProdOrderPosOperationHandlingUnit;
use App\Models\Qualification;
use App\Models\TpmGroup;
use App\Models\HweProdOrderPosOperationOvenProtocol;
use App\Models\MachineUserTime;
use App\Models\Plant;
use App\Models\QualificationUser;
use App\Models\Role;
use Flat3\Lodata\Facades\Lodata;
use Illuminate\Support\Facades\App;
use Illuminate\Support\ServiceProvider;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Spatie\Permission\Models\Permission;
use App\Models\Stock;
use App\Models\UserRegisteredTime;
use App\Models\SectionActivatable;
use App\Models\DataExport;
use App\Models\MachineUserPlanTime;
use App\Models\CommandSchedule;
use App\Models\MetallographyCleanlinessDeterminationAccording;
use App\Models\CalculationMetallographyCleanlinessDeterminationAccording;
use App\Models\CustomerCategory;

// DocVisu Imports
use App\Models\DocVisu\DocVisuDirectory;
use App\Models\DocVisu\DirectoryStructure;
use App\Models\DocVisu\DocumentSection;
use App\Models\DocVisu\DocVisuFile;
use App\Models\DocVisu\FileVersion;
use App\Models\DocVisu\FileNote;
use App\Models\MachineDailyExpectedQuantity;
use App\Models\DocVisu\DocVisuLinking;
use App\Models\InspectionOperationCharacteristic;
use App\Models\InspectionOperationCharacteristicOption;
use App\Models\InspectionPoint;
use App\Models\InspectionPointCharacteristic;
use App\Models\InspectionPointCharacteristicOption;
use App\Models\ProdOrderPosOperationLoadedQuantity;
use App\Models\ProdOrderPosOperationUnloadedQuantity;

// ShiftVisu
use App\Models\ShiftVisu\ShiftVisuIssueType;
use App\Models\ShiftVisu\ShiftVisuComponent;
use App\Models\ShiftVisu\ShiftVisuComponentOption;

// PlanVisu
use App\Models\PlanVisuColorSchemeSorting;
use App\Models\PlanVisuColorScheme;

class LodataServiceProvider extends ServiceProvider
{
    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        $isOdataRequest = request()->is(config('lodata.prefix') . "/*") || request()->is(config('lodata.prefix'));

        if (!App::runningInConsole() && $isOdataRequest) {
            Lodata::discover(Bom::class);
            Lodata::discover(ItemType::class);
            Lodata::discover(ItemState::class);
            Lodata::discover(ItemStateGroup::class);
            Lodata::discover(ItemPlant::class);
            Lodata::discover(ItemStateMachine::class);
            Lodata::discover(Calculation::class);
            Lodata::discover(CalculationHeatTreatment::class);
            Lodata::discover(CalculationAdditionalHeatTreatment::class);
            Lodata::discover(CallOffSimulation::class);
            Lodata::discover(Classification::class);
            Lodata::discover(Crucible::class);
            Lodata::discover(Customer::class);
            Lodata::discover(Country::class);
            Lodata::discover(CalculationDocumentation::class);
            Lodata::discover(CalculationDeformation::class);
            Lodata::discover(CalculationDocumentationCertificate::class);
            Lodata::discover(CalculationResidualMaterial::class);
            Lodata::discover(CalculationMetallography::class);
            Lodata::discover(CalculationTestingScope::class);
            Lodata::discover(CalculationTestingScopeAttestationEntity::class);
            Lodata::discover(CalculationTestingScopeAccordingToTensileTest::class);
            Lodata::discover(CalculationTestingScopeAccordingToImpactTest::class);
            Lodata::discover(CalculationTestingScopeClassifiedBy::class);
            Lodata::discover(CalculationTestingScopeMeltingType::class);
            Lodata::discover(CalculationTestingScopeSampleDepth::class);
            Lodata::discover(CalculationHardenabilityRange::class);
            Lodata::discover(CalculationMaterialAnalysis::class);
            Lodata::discover(CalculationChemAnalysis::class);
            Lodata::discover(Contact::class);
            Lodata::discover(ContactableContact::class);
            Lodata::discover(CustomerMarketSegment::class);
            Lodata::discover(Chat::class);
            Lodata::discover(Message::class);
            Lodata::discover(Documentation::class);
            Lodata::discover(DocumentationCertificate::class);

            // DocVisu
            Lodata::discover(DocVisuDirectory::class);
            Lodata::discover(DocVisuFile::class);
            Lodata::discover(FileVersion::class);
            Lodata::discover(DocumentSection::class);
            Lodata::discover(DirectoryStructure::class);
            Lodata::discover(FileNote::class);
            Lodata::discover(DocVisuLinking::class);
            
            // ShiftVisu
            Lodata::discover(ShiftVisuIssueType::class);
            Lodata::discover(ShiftVisuComponent::class);
            Lodata::discover(ShiftVisuComponentOption::class);

            Lodata::discover(Department::class);
            Lodata::discover(Deformation::class);
            Lodata::discover(CalculationNonDestructiveTesting::class);
            Lodata::discover(CalculationNonDestructiveTestingAttestationEntity::class);
            Lodata::discover(DeliveryTerm::class);
            Lodata::discover(EnergyConsumer::class);
            Lodata::discover(EnergyConsumerMachine::class);
            Lodata::discover(EnergyGateway::class);
            Lodata::discover(EnergyMeter::class);
            Lodata::discover(EnergyConsumption::class);
            Lodata::discover(EnergyMeterReading::class);
            Lodata::discover(Equipment::class);
            Lodata::discover(EmployeeClassification::class);
            Lodata::discover(Hall::class);
            Lodata::discover(HandlingUnit::class);
            Lodata::discover(HweKalkLog::class);
            Lodata::discover(HweQsHb::class);
            Lodata::discover(HweQsHbPos::class);
            Lodata::discover(HweQsImpactTest::class);
            Lodata::discover(HweQsImpactTestPos::class);
            Lodata::discover(HweQsJominyTest::class);
            Lodata::discover(HweQsTensileTest::class);
            Lodata::discover(HweFreightCost::class);
            Lodata::discover(HweMeltAnalysis::class);
            Lodata::discover(HweCertificate::class);
            //Lodata::discover(discoverable: HweMeltType::class);
            Lodata::discover(HweCertificateHweQsSample::class);
            Lodata::discover(Item::class);
            Lodata::discover(Machine::class);
            Lodata::discover(MachineGroup::class);
            Lodata::discover(MarketSegment::class);
            Lodata::discover(Material::class);
            Lodata::discover(MaterialAnalysis::class);
            Lodata::discover(MaterialConsumption::class);
            Lodata::discover(MaterialDatabase::class);
            Lodata::discover(Media::class);
            Lodata::discover(Metallography::class);
            Lodata::discover(MpCost::class);
            Lodata::discover(MpCostMachine::class);
            Lodata::discover(MpOffer::class);
            Lodata::discover(MpMaterial::class);
            Lodata::discover(MpOfferPos::class);
            Lodata::discover(MpPersonnel::class);
            Lodata::discover(MtSpec::class);
            Lodata::discover(MtNorm::class);
            Lodata::discover(MtNormControlUnit::class);
            Lodata::discover(MachineClassification::class);
            Lodata::discover(OfferPosMechanicalProcess::class);
            Lodata::discover(NonDestructiveTesting::class);
            Lodata::discover(NonDestructiveTestingAttestationEntity::class);
            Lodata::discover(Norm::class);
            Lodata::discover(Offer::class);
            Lodata::discover(OfferPos::class);
            Lodata::discover(OfferPosCost::class);
            Lodata::discover(OfferPosRawDimension::class);
            Lodata::discover(OfferPosDimensionShaftUpsetPart::class);
            Lodata::discover(OfferPosDimensionUpsetPartForgedBeam::class);
            Lodata::discover(OperationPlan::class);
            Lodata::discover(OperationPlanPos::class);
            Lodata::discover(OperationControlProfile::class);
            Lodata::discover(OperationPlanPosHeatTreatment::class);
            Lodata::discover(Printer::class);
            Lodata::discover(ProdOrderPosOperation::class);
            Lodata::discover(ProdOrderPosOperationQuantity::class);
            Lodata::discover(PaymentTerm::class);
            Lodata::discover(ProdOrder::class);
            Lodata::discover(ProdOrderPosOperationLoadedQuantity::class);
            Lodata::discover(ProdOrderPosOperationUnloadedQuantity::class);
            Lodata::discover(PotentialClassification::class);
            Lodata::discover(PtNorm::class);
            Lodata::discover(ResidualMaterial::class);
            Lodata::discover(RawDimensionType::class);
            Lodata::discover(RevenueClassification::class);
            Lodata::discover(SalesOpportunity::class);
            Lodata::discover(SalesStatus::class);
            Lodata::discover(SerialNumberProfile::class);
            Lodata::discover(Specification::class);
            Lodata::discover(SequenceOperation::class);
            Lodata::discover(Supplier::class);
            Lodata::discover(Terminal::class);
            Lodata::discover(TestingScope::class);
            Lodata::discover(TestingScopeAccordingToImpactTest::class);
            Lodata::discover(TestingScopeAccordingToTensileTest::class);
            Lodata::discover(TestingScopeAttestationEntity::class);
            Lodata::discover(TestingScopeSampleDepth::class);
            Lodata::discover(TransportOrder::class);
            Lodata::discover(TransportOrderPos::class);
            Lodata::discover(TransportOrderType::class);
            Lodata::discover(User::class);
            Lodata::discover(UsNorm::class);
            Lodata::discover(UsNormAdjustment::class);
            Lodata::discover(UsNormTestSection::class);
            Lodata::discover(UsNormTestScope::class);
            Lodata::discover(UsNormRating::class);
            Lodata::discover(VtNorm::class);
            Lodata::discover(VtNormTestTechnique::class);
            Lodata::discover(VtNormAuxiliaryMean::class);
            Lodata::discover(Warehouse::class);
            Lodata::discover(Capacity::class);
            Lodata::discover(Shift::class);
            Lodata::discover(ShiftModel::class);
            Lodata::discover(ShiftModelShift::class);
            Lodata::discover(HwePackagingCost::class);
            Lodata::discover(HwePackagingCostProductType::class);
            Lodata::discover(HweQsSample::class);
            Lodata::discover(HweQsSamplesProdOrderPos::class);
            Lodata::discover(HweQsGrainSizeTest::class);
            Lodata::discover(HweQsCleanlinessTest::class);
            Lodata::discover(HweQsUsNormTestSection::class);
            Lodata::discover(HweQsUsNormTestScope::class);
            Lodata::discover(HweQsUsNormRating::class);
            Lodata::discover(HweQsUsNormAdjustment::class);
            Lodata::discover(HweQsUsNorm::class);
            Lodata::discover(HweQsMtNorm::class);
            Lodata::discover(HweQsPtNorm::class);
            Lodata::discover(HweQsVtNorm::class);
            Lodata::discover(HardenabilityRange::class);
            Lodata::discover(HweAdditionalCost::class);
            Lodata::discover(HweProdOrderPosOperationOvenProtocol::class);
            Lodata::discover(HweHeatTreatmentCost::class);
            Lodata::discover(HweWorkPlan::class);
            Lodata::discover(HweWorkPlanHeatTreatment::class);
            Lodata::discover(HweWorkPlanAdditionalHeatTreatment::class);
            Lodata::discover(UnitOfMeasure::class);
            Lodata::discover(MarkerRecipe::class);
            Lodata::discover(MarkerRecipePos::class);
            Lodata::discover(MarkerRecipePosBlock::class);
            Lodata::discover(HweRingRollingFactor::class);
            Lodata::discover(HweHeatTreatmentFactor::class);
            Lodata::discover(HweAdditionalCostTrigger::class);
            Lodata::discover(HweOfferPosWorkPlanLeadTime::class);
            Lodata::discover(AbsenceRequest::class);
            Lodata::discover(AbsenceType::class);
            Lodata::discover(Setting::class);
            Lodata::discover(NotificationGroup::class);
            Lodata::discover(NotificationGroupUser::class);
            Lodata::discover(NotificationGroupEmailAddress::class);
            Lodata::discover(NotificationGroupNotificationType::class);
            Lodata::discover(VisibilitySetting::class);
            Lodata::discover(Language::class);
            Lodata::discover(MachineState::class);
            Lodata::discover(MachineProdOrderPosOperationTime::class);
            Lodata::discover(MachineStateGroup::class);
            Lodata::discover(ProdLot::class);
            Lodata::discover(ProdOrderPos::class);
            Lodata::discover(PackagingInstruction::class);
            Lodata::discover(PackagingInstructionPos::class);
            Lodata::discover(ProdOrderPosOperationHandlingUnit::class);
            Lodata::discover(Qualification::class);
            Lodata::discover(QualificationUser::class);
            Lodata::discover(Role::class);
            Lodata::discover(Permission::class);
            Lodata::discover(TpmGroup::class);
            Lodata::discover(ProdOrderPosOperationDelivery::class);
            Lodata::discover(MachineUserTime::class);
            Lodata::discover(Plant::class);
            Lodata::discover(Stock::class);
            Lodata::discover(StorageLocation::class);
            Lodata::discover(StorageType::class);
            Lodata::discover(StorageSection::class);
            Lodata::discover(StorageBin::class);
            Lodata::discover(ProductionSupplyArea::class);
            Lodata::discover(UserRegisteredTime::class);
            Lodata::discover(ProdOrderPosOperationBatch::class);
            Lodata::discover(BomPos::class);
            Lodata::discover(SectionActivatable::class);
            Lodata::discover(DataExport::class);
            Lodata::discover(MachineUserPlanTime::class);
            Lodata::discover(CommandSchedule::class);
            Lodata::discover(CalculationMetallographyCleanlinessDeterminationAccording::class);
            Lodata::discover(MetallographyCleanlinessDeterminationAccording::class);
            Lodata::discover(BacklogItemWeek::class);
            Lodata::discover(MachineDailyExpectedQuantity::class);
            Lodata::discover(CrmAction::class);
            Lodata::discover(CustomerCrmActionLog::class);
            Lodata::discover(Area::class);
            Lodata::discover(CustomerCategory::class);
            Lodata::discover(EightDReport::class);
            Lodata::discover(EightDReportTeam::class);
            Lodata::discover(EightDReportAction::class);
            Lodata::discover(EightDReportFiveWhy::class);
            Lodata::discover(EightDReportIshikawa::class);
            Lodata::discover(HallCapacitySetting::class);
            Lodata::discover(ProdInspectionOperation::class);
            Lodata::discover(InspectionOperationCharacteristic::class);
            Lodata::discover(InspectionOperationCharacteristicOption::class);
            Lodata::discover(InspectionPoint::class);
            Lodata::discover(InspectionPointCharacteristic::class);
            Lodata::discover(InspectionPointCharacteristicOption::class);
            Lodata::discover(PlanVisuColorScheme::class);
            Lodata::discover(PlanVisuColorSchemeSorting::class);
        }
    }
}